#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/lavender

PRODUCT_COPY_FILES += \
    vendor/xiaomi/lavender/proprietary/system_ext/etc/cdma_call_conf.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/cdma_call_conf.xml \
    vendor/xiaomi/lavender/proprietary/system_ext/etc/dpm/dpm.conf:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/dpm/dpm.conf \
    vendor/xiaomi/lavender/proprietary/system_ext/etc/init/dpmd.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/dpmd.rc \
    vendor/xiaomi/lavender/proprietary/system_ext/etc/init/sxrauxd_ext.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/sxrauxd_ext.rc \
    vendor/xiaomi/lavender/proprietary/system_ext/etc/permissions/audiosphere.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/audiosphere.xml \
    vendor/xiaomi/lavender/proprietary/system_ext/etc/permissions/com.qti.dpmframework.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.qti.dpmframework.xml \
    vendor/xiaomi/lavender/proprietary/system_ext/etc/permissions/dpmapi.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/dpmapi.xml \
    vendor/xiaomi/lavender/proprietary/system_ext/etc/permissions/embms-noship_product_privapp_permissions_qti.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/embms-noship_product_privapp_permissions_qti.xml \
    vendor/xiaomi/lavender/proprietary/system_ext/etc/permissions/qcrilhook.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qcrilhook.xml \
    vendor/xiaomi/lavender/proprietary/system_ext/etc/permissions/qti_libpermissions.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qti_libpermissions.xml \
    vendor/xiaomi/lavender/proprietary/system_ext/etc/permissions/qti_permissions.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qti_permissions.xml \
    vendor/xiaomi/lavender/proprietary/system_ext/etc/permissions/telephony_system-ext_privapp-permissions-qti.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/telephony_system-ext_privapp-permissions-qti.xml \
    vendor/xiaomi/lavender/proprietary/system_ext/etc/seccomp_policy/sxraux-arm.policy:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/seccomp_policy/sxraux-arm.policy \
    vendor/xiaomi/lavender/proprietary/system_ext/etc/spn-conf.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/spn-conf.xml \
    vendor/xiaomi/lavender/proprietary/system_ext/etc/sysconfig/qti_whitelist_system_ext.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/sysconfig/qti_whitelist_system_ext.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb \
    vendor/xiaomi/lavender/proprietary/vendor/etc/acdbdata/MTP/MTP_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_General_cal.acdb \
    vendor/xiaomi/lavender/proprietary/vendor/etc/acdbdata/MTP/MTP_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Global_cal.acdb \
    vendor/xiaomi/lavender/proprietary/vendor/etc/acdbdata/MTP/MTP_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Handset_cal.acdb \
    vendor/xiaomi/lavender/proprietary/vendor/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb \
    vendor/xiaomi/lavender/proprietary/vendor/etc/acdbdata/MTP/MTP_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Headset_cal.acdb \
    vendor/xiaomi/lavender/proprietary/vendor/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Speaker_cal.acdb \
    vendor/xiaomi/lavender/proprietary/vendor/etc/acdbdata/MTP/MTP_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_workspaceFile.qwsp \
    vendor/xiaomi/lavender/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/adsp_avs_config.acdb \
    vendor/xiaomi/lavender/proprietary/vendor/etc/camera/GpuKernelRepo.pb:$(TARGET_COPY_OUT_VENDOR)/etc/camera/GpuKernelRepo.pb \
    vendor/xiaomi/lavender/proprietary/vendor/etc/camera/beauty_ui9_intelligent_params.config:$(TARGET_COPY_OUT_VENDOR)/etc/camera/beauty_ui9_intelligent_params.config \
    vendor/xiaomi/lavender/proprietary/vendor/etc/camera/camera_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera_config.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/camera/csidtg_camera.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/csidtg_camera.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/camera/csidtg_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/csidtg_chromatix.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/camera/lavender_imx486_ofilm_i_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/lavender_imx486_ofilm_i_chromatix.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/camera/lavender_imx486_ofilm_i_dw9714_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/lavender_imx486_ofilm_i_dw9714_chromatix.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/camera/lavender_ov02a10_ofilm_i_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/lavender_ov02a10_ofilm_i_chromatix.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/camera/lavender_ov02a10_sunny_ii_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/lavender_ov02a10_sunny_ii_chromatix.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/camera/lavender_ov12a10_sunny_ii_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/lavender_ov12a10_sunny_ii_chromatix.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/camera/lavender_ov13855_ofilm_global_i_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/lavender_ov13855_ofilm_global_i_chromatix.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/camera/lavender_ov13855_ofilm_i_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/lavender_ov13855_ofilm_i_chromatix.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/camera/lavender_ov13855_ofilm_india_i_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/lavender_ov13855_ofilm_india_i_chromatix.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/camera/lavender_ov13855_sunny_global_ii_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/lavender_ov13855_sunny_global_ii_chromatix.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/camera/lavender_ov13855_sunny_ii_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/lavender_ov13855_sunny_ii_chromatix.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/camera/lavender_ov13855_sunny_india_ii_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/lavender_ov13855_sunny_india_ii_chromatix.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/camera/lavender_s5k5e8_ofilm_cn_i_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/lavender_s5k5e8_ofilm_cn_i_chromatix.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/camera/lavender_s5k5e8_sunny_cn_ii_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/lavender_s5k5e8_sunny_cn_ii_chromatix.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/camera/lavender_s5kgm1_ofilm_i_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/lavender_s5kgm1_ofilm_i_chromatix.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/camera/lavender_s5kgm1_ofilm_india_i_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/lavender_s5kgm1_ofilm_india_i_chromatix.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/camera/lavender_s5kgm1_sunny_ii_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/lavender_s5kgm1_sunny_ii_chromatix.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/camera/lavender_s5kgm1_sunny_india_ii_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/lavender_s5kgm1_sunny_india_ii_chromatix.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/camera/lf_facerank_model.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/lf_facerank_model.bin \
    vendor/xiaomi/lavender/proprietary/vendor/etc/camera/megviifacepp_model:$(TARGET_COPY_OUT_VENDOR)/etc/camera/megviifacepp_model \
    vendor/xiaomi/lavender/proprietary/vendor/etc/camera/model_back.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model_back.dlc \
    vendor/xiaomi/lavender/proprietary/vendor/etc/camera/model_front.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model_front.dlc \
    vendor/xiaomi/lavender/proprietary/vendor/etc/camera/sdm_ys_32p_120_21_5_perturb50.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sdm_ys_32p_120_21_5_perturb50.bin \
    vendor/xiaomi/lavender/proprietary/vendor/etc/cne/mwqem.conf:$(TARGET_COPY_OUT_VENDOR)/etc/cne/mwqem.conf \
    vendor/xiaomi/lavender/proprietary/vendor/etc/cne/profileMwqem.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/profileMwqem.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile1.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile2.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile3.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile4.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile5.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile6.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile1.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile15.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile15.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile16.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile16.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile17.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile17.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile18.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile18.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile19.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile19.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile2.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile20.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile20.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile21.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile21.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile3.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile32.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile32.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile4.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile5.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile6.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile7.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile7.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile1.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile2.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile3.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile4.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile5.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile6.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/data/dsi_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/dsi_config.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/data/netmgr_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/netmgr_config.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/default-permissions/com.qualcomm.qti.cne.xml:$(TARGET_COPY_OUT_VENDOR)/etc/default-permissions/com.qualcomm.qti.cne.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/diracmobile.config:$(TARGET_COPY_OUT_VENDOR)/etc/diracmobile.config \
    vendor/xiaomi/lavender/proprietary/vendor/etc/diracvdd.bin:$(TARGET_COPY_OUT_VENDOR)/etc/diracvdd.bin \
    vendor/xiaomi/lavender/proprietary/vendor/etc/gpfspath_oem_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gpfspath_oem_config.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/init/android.hardware.bluetooth@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.0-service-qti.rc \
    vendor/xiaomi/lavender/proprietary/vendor/etc/init/android.hardware.drm@1.4-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.4-service.widevine.rc \
    vendor/xiaomi/lavender/proprietary/vendor/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc \
    vendor/xiaomi/lavender/proprietary/vendor/etc/init/android.hardware.keymaster@4.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@4.0-service-qti.rc \
    vendor/xiaomi/lavender/proprietary/vendor/etc/init/cnd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/cnd.rc \
    vendor/xiaomi/lavender/proprietary/vendor/etc/init/dataadpl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataadpl.rc \
    vendor/xiaomi/lavender/proprietary/vendor/etc/init/dataqti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataqti.rc \
    vendor/xiaomi/lavender/proprietary/vendor/etc/init/dpmQmiMgr.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dpmQmiMgr.rc \
    vendor/xiaomi/lavender/proprietary/vendor/etc/init/ims_rtp_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ims_rtp_daemon.rc \
    vendor/xiaomi/lavender/proprietary/vendor/etc/init/imsdatadaemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsdatadaemon.rc \
    vendor/xiaomi/lavender/proprietary/vendor/etc/init/imsqmidaemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsqmidaemon.rc \
    vendor/xiaomi/lavender/proprietary/vendor/etc/init/imsrcsd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsrcsd.rc \
    vendor/xiaomi/lavender/proprietary/vendor/etc/init/init-qcril-data.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init-qcril-data.rc \
    vendor/xiaomi/lavender/proprietary/vendor/etc/init/init.time_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.time_daemon.rc \
    vendor/xiaomi/lavender/proprietary/vendor/etc/init/init_thermal-engine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init_thermal-engine.rc \
    vendor/xiaomi/lavender/proprietary/vendor/etc/init/netmgrd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/netmgrd.rc \
    vendor/xiaomi/lavender/proprietary/vendor/etc/init/port-bridge.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/port-bridge.rc \
    vendor/xiaomi/lavender/proprietary/vendor/etc/init/qcrild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qcrild.rc \
    vendor/xiaomi/lavender/proprietary/vendor/etc/init/vendor.display.color@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.display.color@1.0-service.rc \
    vendor/xiaomi/lavender/proprietary/vendor/etc/init/vendor.qti.adsprpc-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.adsprpc-service.rc \
    vendor/xiaomi/lavender/proprietary/vendor/etc/init/vendor.qti.cdsprpc-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.cdsprpc-service.rc \
    vendor/xiaomi/lavender/proprietary/vendor/etc/init/vendor.qti.esepowermanager@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.esepowermanager@1.1-service.rc \
    vendor/xiaomi/lavender/proprietary/vendor/etc/init/vendor.qti.hardware.alarm@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.alarm@1.0-service.rc \
    vendor/xiaomi/lavender/proprietary/vendor/etc/init/vendor.qti.hardware.capabilityconfigstore@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.capabilityconfigstore@1.0-service.rc \
    vendor/xiaomi/lavender/proprietary/vendor/etc/init/vendor.qti.hardware.dsp@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.dsp@1.0-service.rc \
    vendor/xiaomi/lavender/proprietary/vendor/etc/init/vendor.qti.hardware.qseecom@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.qseecom@1.0-service.rc \
    vendor/xiaomi/lavender/proprietary/vendor/etc/init/vendor.qti.hardware.qteeconnector@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.qteeconnector@1.0-service.rc \
    vendor/xiaomi/lavender/proprietary/vendor/etc/init/vendor.qti.hardware.soter@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.soter@1.0-service.rc \
    vendor/xiaomi/lavender/proprietary/vendor/etc/init/vendor.qti.hardware.tui_comm@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.tui_comm@1.0-service-qti.rc \
    vendor/xiaomi/lavender/proprietary/vendor/etc/init/vendor.qti.rmt_storage.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.rmt_storage.rc \
    vendor/xiaomi/lavender/proprietary/vendor/etc/init/vendor.qti.tftp.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.tftp.rc \
    vendor/xiaomi/lavender/proprietary/vendor/etc/init/vendor.xiaomi.hardware.mlipay@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.xiaomi.hardware.mlipay@1.1-service.rc \
    vendor/xiaomi/lavender/proprietary/vendor/etc/qdcm_calib_data_boe_td4320_fhdplus_video_mode_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_boe_td4320_fhdplus_video_mode_dsi_panel.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/qdcm_calib_data_shenchao_nt36672a_fhdplus_video_mode_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_shenchao_nt36672a_fhdplus_video_mode_dsi_panel.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/qdcm_calib_data_tianma_nt36672a_fhdplus_video_mode_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_tianma_nt36672a_fhdplus_video_mode_dsi_panel.xml \
    vendor/xiaomi/lavender/proprietary/vendor/etc/seccomp_policy/imsrtp.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/imsrtp.policy \
    vendor/xiaomi/lavender/proprietary/vendor/etc/seccomp_policy/qti-systemd.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/qti-systemd.policy \
    vendor/xiaomi/lavender/proprietary/vendor/etc/seccomp_policy/vendor.qti.hardware.dsp.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/vendor.qti.hardware.dsp.policy \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/a512_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.b00 \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/a512_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.b01 \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/a512_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.b02 \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/a512_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.elf \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/a512_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.mdt \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/a530_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_gpmu.fw2 \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/a530_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pfp.fw \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/a530_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pm4.fw \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/a530v1_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v1_pfp.fw \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/a530v1_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v1_pm4.fw \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/a530v2_seq.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v2_seq.fw2 \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/a530v3_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v3_gpmu.fw2 \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/a530v3_seq.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v3_seq.fw2 \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/a540_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_gpmu.fw2 \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/cpp_firmware_v1_10_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_10_0.fw \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/cpp_firmware_v1_12_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_12_0.fw \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/cpp_firmware_v1_1_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_1.fw \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/cpp_firmware_v1_1_6.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_6.fw \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/cpp_firmware_v1_2_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_2_0.fw \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/cpp_firmware_v1_4_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_4_0.fw \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/cpp_firmware_v1_5_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_0.fw \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/cpp_firmware_v1_5_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_1.fw \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/cpp_firmware_v1_5_2.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_2.fw \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/cpp_firmware_v1_6_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_6_0.fw \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/cpp_firmware_v1_8_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_8_0.fw \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/fpctzappfingerprint.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b00 \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/fpctzappfingerprint.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b01 \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/fpctzappfingerprint.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b02 \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/fpctzappfingerprint.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b03 \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/fpctzappfingerprint.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b04 \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/fpctzappfingerprint.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b05 \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/fpctzappfingerprint.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b06 \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/fpctzappfingerprint.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b07 \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/fpctzappfingerprint.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.mdt \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/goodixfp.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b00 \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/goodixfp.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b01 \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/goodixfp.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b02 \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/goodixfp.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b03 \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/goodixfp.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b04 \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/goodixfp.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b05 \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/goodixfp.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b06 \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/goodixfp.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b07 \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/goodixfp.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.mdt \
    vendor/xiaomi/lavender/proprietary/vendor/firmware/voice_amodel.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/voice_amodel.bin \
    vendor/xiaomi/lavender/proprietary/vendor/lib/mibokeh_660_opencl.bin:$(TARGET_COPY_OUT_VENDOR)/lib/mibokeh_660_opencl.bin \
    vendor/xiaomi/lavender/proprietary/vendor/radio/qcril_database/qcril.db:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/qcril.db \
    vendor/xiaomi/lavender/proprietary/vendor/radio/qcril_database/upgrade/0_initial.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/0_initial.sql \
    vendor/xiaomi/lavender/proprietary/vendor/radio/qcril_database/upgrade/10_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/10_version_update_ecc_table.sql \
    vendor/xiaomi/lavender/proprietary/vendor/radio/qcril_database/upgrade/11_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/11_version_update_ecc_table.sql \
    vendor/xiaomi/lavender/proprietary/vendor/radio/qcril_database/upgrade/1_version_intro.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/1_version_intro.sql \
    vendor/xiaomi/lavender/proprietary/vendor/radio/qcril_database/upgrade/2_version_add_wps_config.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/2_version_add_wps_config.sql \
    vendor/xiaomi/lavender/proprietary/vendor/radio/qcril_database/upgrade/3_version_update_wps_config.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/3_version_update_wps_config.sql \
    vendor/xiaomi/lavender/proprietary/vendor/radio/qcril_database/upgrade/4_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/4_version_update_ecc_table.sql \
    vendor/xiaomi/lavender/proprietary/vendor/radio/qcril_database/upgrade/5_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/5_version_update_ecc_table.sql \
    vendor/xiaomi/lavender/proprietary/vendor/radio/qcril_database/upgrade/6_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/6_version_update_ecc_table.sql \
    vendor/xiaomi/lavender/proprietary/vendor/radio/qcril_database/upgrade/7_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/7_version_update_ecc_table.sql \
    vendor/xiaomi/lavender/proprietary/vendor/radio/qcril_database/upgrade/8_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/8_version_update_ecc_table.sql \
    vendor/xiaomi/lavender/proprietary/vendor/radio/qcril_database/upgrade/9_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/9_version_update_ecc_table.sql

PRODUCT_PACKAGES += \
    libsdm-disp-apis \
    btaudio_offload_if \
    com.qualcomm.qti.dpm.api@1.0_vendor \
    eglSubDriverAndroid \
    libEGL_adreno \
    libGLESv1_CM_adreno \
    libGLESv2_adreno \
    libq3dtools_adreno \
    libq3dtools_esx \
    android.hardware.bluetooth@1.0-impl-qti \
    android.hardware.gatekeeper@1.0-impl-qti \
    android.hardware.keymaster@3.0-impl-qti \
    audio.bluetooth_qti.default \
    gatekeeper.sdm660 \
    vendor.qti.esepowermanager@1.1-impl \
    vendor.qti.hardware.bluetooth_audio@2.0-impl \
    vendor.qti.hardware.bluetooth_audio@2.1-impl \
    vendor.qti.hardware.bluetooth_sar@1.1-impl \
    vendor.qti.hardware.btconfigstore@1.0-impl \
    vendor.qti.hardware.btconfigstore@2.0-impl \
    vendor.qti.hardware.qseecom@1.0-impl \
    vendor.qti.hardware.qteeconnector@1.0-impl \
    vulkan.adreno \
    libC2D2 \
    libCB \
    libFlacSwDec \
    libGPreqcancel_svc \
    libOpenCL \
    libQSEEComAPI \
    libQTEEConnector_vendor \
    libVkLayer_q3dtools \
    libacdb-fts \
    libacdbloader \
    libacdbrtac \
    libadiertac \
    libadreno_utils \
    libadsp_default_listener \
    libadsprpc \
    libaudcal \
    libaudioalsa \
    libaudioconfigstore \
    libaudioparsers \
    libbluetooth_audio_session_qti \
    libbluetooth_audio_session_qti_2_1 \
    libbt-hidlclient \
    libbtnv \
    libc2d30_bltlib \
    libcdsp_default_listener \
    libcdsprpc \
    libcpion \
    libdiag \
    libdsutils \
    libfastcvadsp_stub \
    libfastcvopt \
    libfastrpc_utf_stub \
    libgcs-calwrapper \
    libgcs-ipc \
    libgcs-osal \
    libgcs \
    libgpudataproducer \
    libgsl \
    libhdr_tm \
    libidl \
    libkeymasterdeviceutils \
    libkeymasterprovision \
    libkeymasterutils \
    libllvm-glnext \
    libllvm-qcom \
    libmdmdetect \
    libmdsprpc \
    libminkdescriptor \
    libmm-hdcpmgr \
    libmmcamera_dbg \
    libmulawdec \
    libnative-api \
    libqcbor \
    libqcci_legacy \
    libqdi \
    libqdp \
    libqmi \
    libqmi_cci \
    libqmi_client_helper \
    libqmi_client_qmux \
    libqmi_common_so \
    libqmi_csi \
    libqmi_encdec \
    libqmi_legacy \
    libqmiservices \
    libqrtr \
    libqseed3 \
    libqtigef \
    libqtikeymaster4 \
    librs_adreno \
    libscveCommon \
    libscveCommon_stub \
    libscveObjectSegmentation \
    libscveObjectSegmentation_stub \
    libscveObjectTracker \
    libscveObjectTracker_stub \
    libsdedrm \
    libsdm-color \
    libsdm-diag \
    libsdm-disp-vndapis \
    libsdmextension \
    libsdsprpc \
    libsensor1 \
    libsensor_reg \
    libsoc_helper \
    libssc_default_listener \
    libsysmon_cdsp_skel \
    libthermalclient \
    libtime_genoff \
    libtinyxml2_1 \
    sensor_calibrate \
    sensors.ssc \
    libasphere \
    libqcbassboost \
    libqcreverb \
    libqcvirt \
    libshoebox \
    vendor.display.color@1.0 \
    vendor.display.color@1.1 \
    vendor.display.color@1.2 \
    vendor.display.postproc@1.0 \
    vendor.qti.esepowermanager@1.0 \
    vendor.qti.esepowermanager@1.1 \
    vendor.qti.hardware.bluetooth_sar@1.0 \
    vendor.qti.hardware.bluetooth_sar@1.1 \
    vendor.qti.hardware.dsp@1.0 \
    vendor.qti.hardware.fm@1.0 \
    vendor.qti.hardware.mwqemadapter@1.0_vendor \
    vendor.qti.hardware.qseecom@1.0_vendor \
    vendor.qti.hardware.qteeconnector@1.0 \
    vendor.qti.hardware.scve.objecttracker@1.0 \
    vendor.qti.hardware.scve.panorama@1.0 \
    vendor.qti.hardware.tui_comm@1.0_vendor \
    vendor.qti.hardware.vpp@1.1 \
    vendor.qti.hardware.vpp@1.2 \
    libDiracAPI_SHARED \
    libSNPE \
    libSonyIMX376C3RmscLibrary \
    libSonyIMX376KRmscLibrary \
    libVDClearShot \
    libVDSuperPhotoAPI \
    lib_lowlight \
    libactuator_lavender_imx486_ofilm_i_bu64982 \
    libactuator_lavender_imx486_ofilm_i_dw9714 \
    libactuator_lavender_ov12a10_sunny_ii_dw9714 \
    libactuator_lavender_s5kgm1_ofilm_i_dw9800 \
    libactuator_lavender_s5kgm1_sunny_ii_dw9800 \
    libadm \
    libadpcmdec \
    libadsp_hvx_callback_skel \
    libadsp_hvx_stub \
    libarcsoft_dualcam_refocus \
    libarcsoft_high_dynamic_range \
    libarcsoft_supernight \
    libc++_shared \
    libcamera_scene \
    libchromatix_csidtg_common \
    libchromatix_csidtg_cpp_preview \
    libchromatix_csidtg_postproc \
    libchromatix_csidtg_preview \
    libchromatix_csidtg_zsl_preview \
    libchromatix_lavender_imx486_ofilm_i_bokeh_preview_3a \
    libchromatix_lavender_imx486_ofilm_i_common \
    libchromatix_lavender_imx486_ofilm_i_cpp_hfr_120 \
    libchromatix_lavender_imx486_ofilm_i_cpp_hfr_60 \
    libchromatix_lavender_imx486_ofilm_i_cpp_hfr_90 \
    libchromatix_lavender_imx486_ofilm_i_cpp_liveshot \
    libchromatix_lavender_imx486_ofilm_i_cpp_preview \
    libchromatix_lavender_imx486_ofilm_i_cpp_preview_sn \
    libchromatix_lavender_imx486_ofilm_i_cpp_preview_sr \
    libchromatix_lavender_imx486_ofilm_i_cpp_preview_video \
    libchromatix_lavender_imx486_ofilm_i_cpp_snapshot \
    libchromatix_lavender_imx486_ofilm_i_cpp_snapshot_bokeh \
    libchromatix_lavender_imx486_ofilm_i_cpp_snapshot_hdr \
    libchromatix_lavender_imx486_ofilm_i_cpp_snapshot_hht \
    libchromatix_lavender_imx486_ofilm_i_cpp_snapshot_sn \
    libchromatix_lavender_imx486_ofilm_i_cpp_snapshot_sr \
    libchromatix_lavender_imx486_ofilm_i_cpp_video \
    libchromatix_lavender_imx486_ofilm_i_cpp_video_weixin \
    libchromatix_lavender_imx486_ofilm_i_cpp_video_weixin_res1 \
    libchromatix_lavender_imx486_ofilm_i_default_preview_3a \
    libchromatix_lavender_imx486_ofilm_i_default_video_3a \
    libchromatix_lavender_imx486_ofilm_i_dw9714_bokeh_preview_3a \
    libchromatix_lavender_imx486_ofilm_i_dw9714_common \
    libchromatix_lavender_imx486_ofilm_i_dw9714_cpp_hfr_120 \
    libchromatix_lavender_imx486_ofilm_i_dw9714_cpp_hfr_60 \
    libchromatix_lavender_imx486_ofilm_i_dw9714_cpp_hfr_90 \
    libchromatix_lavender_imx486_ofilm_i_dw9714_cpp_liveshot \
    libchromatix_lavender_imx486_ofilm_i_dw9714_cpp_preview \
    libchromatix_lavender_imx486_ofilm_i_dw9714_cpp_preview_sn \
    libchromatix_lavender_imx486_ofilm_i_dw9714_cpp_preview_sr \
    libchromatix_lavender_imx486_ofilm_i_dw9714_cpp_preview_video \
    libchromatix_lavender_imx486_ofilm_i_dw9714_cpp_snapshot \
    libchromatix_lavender_imx486_ofilm_i_dw9714_cpp_snapshot_bokeh \
    libchromatix_lavender_imx486_ofilm_i_dw9714_cpp_snapshot_hdr \
    libchromatix_lavender_imx486_ofilm_i_dw9714_cpp_snapshot_hht \
    libchromatix_lavender_imx486_ofilm_i_dw9714_cpp_snapshot_sn \
    libchromatix_lavender_imx486_ofilm_i_dw9714_cpp_snapshot_sr \
    libchromatix_lavender_imx486_ofilm_i_dw9714_cpp_video \
    libchromatix_lavender_imx486_ofilm_i_dw9714_cpp_video_weixin \
    libchromatix_lavender_imx486_ofilm_i_dw9714_cpp_video_weixin_res1 \
    libchromatix_lavender_imx486_ofilm_i_dw9714_default_preview_3a \
    libchromatix_lavender_imx486_ofilm_i_dw9714_default_video_3a \
    libchromatix_lavender_imx486_ofilm_i_dw9714_hfr_120 \
    libchromatix_lavender_imx486_ofilm_i_dw9714_hfr_120_3a \
    libchromatix_lavender_imx486_ofilm_i_dw9714_hfr_60 \
    libchromatix_lavender_imx486_ofilm_i_dw9714_hfr_60_3a \
    libchromatix_lavender_imx486_ofilm_i_dw9714_hfr_90 \
    libchromatix_lavender_imx486_ofilm_i_dw9714_hfr_90_3a \
    libchromatix_lavender_imx486_ofilm_i_dw9714_pano_preview_3a \
    libchromatix_lavender_imx486_ofilm_i_dw9714_postproc \
    libchromatix_lavender_imx486_ofilm_i_dw9714_preview \
    libchromatix_lavender_imx486_ofilm_i_dw9714_preview_cts \
    libchromatix_lavender_imx486_ofilm_i_dw9714_snapshot \
    libchromatix_lavender_imx486_ofilm_i_dw9714_snapshot_bokeh \
    libchromatix_lavender_imx486_ofilm_i_dw9714_snapshot_cts \
    libchromatix_lavender_imx486_ofilm_i_dw9714_snapshot_hdr \
    libchromatix_lavender_imx486_ofilm_i_dw9714_snapshot_sn \
    libchromatix_lavender_imx486_ofilm_i_dw9714_video \
    libchromatix_lavender_imx486_ofilm_i_dw9714_video_weixin \
    libchromatix_lavender_imx486_ofilm_i_dw9714_video_weixin_res1 \
    libchromatix_lavender_imx486_ofilm_i_dw9714_weixin_video_3a \
    libchromatix_lavender_imx486_ofilm_i_dw9714_weixin_video_3a_res1 \
    libchromatix_lavender_imx486_ofilm_i_dw9714_zsl_preview_3a \
    libchromatix_lavender_imx486_ofilm_i_dw9714_zsl_preview_3a_sn \
    libchromatix_lavender_imx486_ofilm_i_dw9714_zsl_video_3a \
    libchromatix_lavender_imx486_ofilm_i_hfr_120 \
    libchromatix_lavender_imx486_ofilm_i_hfr_120_3a \
    libchromatix_lavender_imx486_ofilm_i_hfr_60 \
    libchromatix_lavender_imx486_ofilm_i_hfr_60_3a \
    libchromatix_lavender_imx486_ofilm_i_hfr_90 \
    libchromatix_lavender_imx486_ofilm_i_hfr_90_3a \
    libchromatix_lavender_imx486_ofilm_i_pano_preview_3a \
    libchromatix_lavender_imx486_ofilm_i_postproc \
    libchromatix_lavender_imx486_ofilm_i_preview \
    libchromatix_lavender_imx486_ofilm_i_preview_cts \
    libchromatix_lavender_imx486_ofilm_i_snapshot \
    libchromatix_lavender_imx486_ofilm_i_snapshot_bokeh \
    libchromatix_lavender_imx486_ofilm_i_snapshot_cts \
    libchromatix_lavender_imx486_ofilm_i_snapshot_hdr \
    libchromatix_lavender_imx486_ofilm_i_snapshot_sn \
    libchromatix_lavender_imx486_ofilm_i_video \
    libchromatix_lavender_imx486_ofilm_i_video_weixin \
    libchromatix_lavender_imx486_ofilm_i_video_weixin_res1 \
    libchromatix_lavender_imx486_ofilm_i_weixin_video_3a \
    libchromatix_lavender_imx486_ofilm_i_weixin_video_3a_res1 \
    libchromatix_lavender_imx486_ofilm_i_zsl_preview_3a \
    libchromatix_lavender_imx486_ofilm_i_zsl_preview_3a_sn \
    libchromatix_lavender_imx486_ofilm_i_zsl_video_3a \
    libchromatix_lavender_ov02a10_ofilm_i_common \
    libchromatix_lavender_ov02a10_ofilm_i_cpp_liveshot \
    libchromatix_lavender_ov02a10_ofilm_i_cpp_preview \
    libchromatix_lavender_ov02a10_ofilm_i_cpp_snapshot \
    libchromatix_lavender_ov02a10_ofilm_i_cpp_video \
    libchromatix_lavender_ov02a10_ofilm_i_default_preview_3a \
    libchromatix_lavender_ov02a10_ofilm_i_default_video \
    libchromatix_lavender_ov02a10_ofilm_i_default_video_3a \
    libchromatix_lavender_ov02a10_ofilm_i_postproc \
    libchromatix_lavender_ov02a10_ofilm_i_preview \
    libchromatix_lavender_ov02a10_ofilm_i_snapshot \
    libchromatix_lavender_ov02a10_ofilm_i_zsl_preview_3a \
    libchromatix_lavender_ov02a10_ofilm_i_zsl_video_3a \
    libchromatix_lavender_ov02a10_sunny_ii_common \
    libchromatix_lavender_ov02a10_sunny_ii_cpp_liveshot \
    libchromatix_lavender_ov02a10_sunny_ii_cpp_preview \
    libchromatix_lavender_ov02a10_sunny_ii_cpp_snapshot \
    libchromatix_lavender_ov02a10_sunny_ii_cpp_video \
    libchromatix_lavender_ov02a10_sunny_ii_default_preview_3a \
    libchromatix_lavender_ov02a10_sunny_ii_default_video \
    libchromatix_lavender_ov02a10_sunny_ii_default_video_3a \
    libchromatix_lavender_ov02a10_sunny_ii_postproc \
    libchromatix_lavender_ov02a10_sunny_ii_preview \
    libchromatix_lavender_ov02a10_sunny_ii_snapshot \
    libchromatix_lavender_ov02a10_sunny_ii_zsl_preview_3a \
    libchromatix_lavender_ov02a10_sunny_ii_zsl_video_3a \
    libchromatix_lavender_ov12a10_sunny_ii_4k_preview_3a \
    libchromatix_lavender_ov12a10_sunny_ii_4k_video_3a \
    libchromatix_lavender_ov12a10_sunny_ii_bokeh_preview_3a \
    libchromatix_lavender_ov12a10_sunny_ii_common \
    libchromatix_lavender_ov12a10_sunny_ii_cpp_hfr_120 \
    libchromatix_lavender_ov12a10_sunny_ii_cpp_hfr_60 \
    libchromatix_lavender_ov12a10_sunny_ii_cpp_hfr_90 \
    libchromatix_lavender_ov12a10_sunny_ii_cpp_liveshot \
    libchromatix_lavender_ov12a10_sunny_ii_cpp_preview \
    libchromatix_lavender_ov12a10_sunny_ii_cpp_preview_sn \
    libchromatix_lavender_ov12a10_sunny_ii_cpp_preview_sr \
    libchromatix_lavender_ov12a10_sunny_ii_cpp_preview_video \
    libchromatix_lavender_ov12a10_sunny_ii_cpp_snapshot \
    libchromatix_lavender_ov12a10_sunny_ii_cpp_snapshot_bokeh \
    libchromatix_lavender_ov12a10_sunny_ii_cpp_snapshot_hdr \
    libchromatix_lavender_ov12a10_sunny_ii_cpp_snapshot_hht \
    libchromatix_lavender_ov12a10_sunny_ii_cpp_snapshot_sn \
    libchromatix_lavender_ov12a10_sunny_ii_cpp_snapshot_sr \
    libchromatix_lavender_ov12a10_sunny_ii_cpp_video \
    libchromatix_lavender_ov12a10_sunny_ii_cpp_video_4k \
    libchromatix_lavender_ov12a10_sunny_ii_cpp_video_weixin \
    libchromatix_lavender_ov12a10_sunny_ii_cpp_video_weixin_res1 \
    libchromatix_lavender_ov12a10_sunny_ii_default_preview_3a \
    libchromatix_lavender_ov12a10_sunny_ii_default_video \
    libchromatix_lavender_ov12a10_sunny_ii_default_video_3a \
    libchromatix_lavender_ov12a10_sunny_ii_default_video_4k \
    libchromatix_lavender_ov12a10_sunny_ii_hfr_120 \
    libchromatix_lavender_ov12a10_sunny_ii_hfr_120_3a \
    libchromatix_lavender_ov12a10_sunny_ii_hfr_60 \
    libchromatix_lavender_ov12a10_sunny_ii_hfr_60_3a \
    libchromatix_lavender_ov12a10_sunny_ii_hfr_60_its \
    libchromatix_lavender_ov12a10_sunny_ii_hfr_90 \
    libchromatix_lavender_ov12a10_sunny_ii_hfr_90_3a \
    libchromatix_lavender_ov12a10_sunny_ii_postproc \
    libchromatix_lavender_ov12a10_sunny_ii_preview \
    libchromatix_lavender_ov12a10_sunny_ii_snapshot \
    libchromatix_lavender_ov12a10_sunny_ii_snapshot_bokeh \
    libchromatix_lavender_ov12a10_sunny_ii_snapshot_hdr \
    libchromatix_lavender_ov12a10_sunny_ii_snapshot_sn \
    libchromatix_lavender_ov12a10_sunny_ii_video_weixin \
    libchromatix_lavender_ov12a10_sunny_ii_video_weixin_res1 \
    libchromatix_lavender_ov12a10_sunny_ii_weixin_video_3a \
    libchromatix_lavender_ov12a10_sunny_ii_weixin_video_3a_res1 \
    libchromatix_lavender_ov12a10_sunny_ii_zsl_preview_3a \
    libchromatix_lavender_ov12a10_sunny_ii_zsl_preview_3a_sn \
    libchromatix_lavender_ov12a10_sunny_ii_zsl_preview_cts \
    libchromatix_lavender_ov12a10_sunny_ii_zsl_video_3a \
    libchromatix_lavender_ov13855_ofilm_global_i_common \
    libchromatix_lavender_ov13855_ofilm_global_i_cpp_ds_chromatix \
    libchromatix_lavender_ov13855_ofilm_global_i_cpp_hfr_120 \
    libchromatix_lavender_ov13855_ofilm_global_i_cpp_hfr_60 \
    libchromatix_lavender_ov13855_ofilm_global_i_cpp_hfr_90 \
    libchromatix_lavender_ov13855_ofilm_global_i_cpp_liveshot \
    libchromatix_lavender_ov13855_ofilm_global_i_cpp_preview \
    libchromatix_lavender_ov13855_ofilm_global_i_cpp_preview_video \
    libchromatix_lavender_ov13855_ofilm_global_i_cpp_snapshot \
    libchromatix_lavender_ov13855_ofilm_global_i_cpp_snapshot_hdr \
    libchromatix_lavender_ov13855_ofilm_global_i_cpp_snapshot_mfnr \
    libchromatix_lavender_ov13855_ofilm_global_i_cpp_us_chromatix \
    libchromatix_lavender_ov13855_ofilm_global_i_cpp_video \
    libchromatix_lavender_ov13855_ofilm_global_i_cpp_video_face \
    libchromatix_lavender_ov13855_ofilm_global_i_cpp_video_full \
    libchromatix_lavender_ov13855_ofilm_global_i_cpp_video_weixin \
    libchromatix_lavender_ov13855_ofilm_global_i_cpp_video_weixin_res1 \
    libchromatix_lavender_ov13855_ofilm_global_i_default_preview_bu64297 \
    libchromatix_lavender_ov13855_ofilm_global_i_default_video \
    libchromatix_lavender_ov13855_ofilm_global_i_default_video_bu64297 \
    libchromatix_lavender_ov13855_ofilm_global_i_default_video_bu64297_douyin \
    libchromatix_lavender_ov13855_ofilm_global_i_face_video_3a \
    libchromatix_lavender_ov13855_ofilm_global_i_flash_cpp_liveshot \
    libchromatix_lavender_ov13855_ofilm_global_i_flash_cpp_preview \
    libchromatix_lavender_ov13855_ofilm_global_i_flash_cpp_snapshot \
    libchromatix_lavender_ov13855_ofilm_global_i_flash_cpp_video \
    libchromatix_lavender_ov13855_ofilm_global_i_flash_preview \
    libchromatix_lavender_ov13855_ofilm_global_i_flash_preview_3a \
    libchromatix_lavender_ov13855_ofilm_global_i_flash_snapshot \
    libchromatix_lavender_ov13855_ofilm_global_i_flash_video \
    libchromatix_lavender_ov13855_ofilm_global_i_flash_video_3a \
    libchromatix_lavender_ov13855_ofilm_global_i_hfr_120 \
    libchromatix_lavender_ov13855_ofilm_global_i_hfr_120_bu64297 \
    libchromatix_lavender_ov13855_ofilm_global_i_hfr_60 \
    libchromatix_lavender_ov13855_ofilm_global_i_hfr_60_bu64297 \
    libchromatix_lavender_ov13855_ofilm_global_i_hfr_90 \
    libchromatix_lavender_ov13855_ofilm_global_i_hfr_90_bu64297 \
    libchromatix_lavender_ov13855_ofilm_global_i_liveshot \
    libchromatix_lavender_ov13855_ofilm_global_i_postproc \
    libchromatix_lavender_ov13855_ofilm_global_i_preview \
    libchromatix_lavender_ov13855_ofilm_global_i_snapshot \
    libchromatix_lavender_ov13855_ofilm_global_i_snapshot_hdr \
    libchromatix_lavender_ov13855_ofilm_global_i_video_face \
    libchromatix_lavender_ov13855_ofilm_global_i_video_full \
    libchromatix_lavender_ov13855_ofilm_global_i_video_weixin \
    libchromatix_lavender_ov13855_ofilm_global_i_video_weixin_res1 \
    libchromatix_lavender_ov13855_ofilm_global_i_weixin_video_3a \
    libchromatix_lavender_ov13855_ofilm_global_i_weixin_video_3a_res1 \
    libchromatix_lavender_ov13855_ofilm_global_i_zsl_preview_bu64297 \
    libchromatix_lavender_ov13855_ofilm_global_i_zsl_video_bu64297 \
    libchromatix_lavender_ov13855_ofilm_i_common \
    libchromatix_lavender_ov13855_ofilm_i_cpp_ds_chromatix \
    libchromatix_lavender_ov13855_ofilm_i_cpp_hfr_120 \
    libchromatix_lavender_ov13855_ofilm_i_cpp_hfr_60 \
    libchromatix_lavender_ov13855_ofilm_i_cpp_hfr_90 \
    libchromatix_lavender_ov13855_ofilm_i_cpp_liveshot \
    libchromatix_lavender_ov13855_ofilm_i_cpp_preview \
    libchromatix_lavender_ov13855_ofilm_i_cpp_preview_video \
    libchromatix_lavender_ov13855_ofilm_i_cpp_snapshot \
    libchromatix_lavender_ov13855_ofilm_i_cpp_snapshot_hdr \
    libchromatix_lavender_ov13855_ofilm_i_cpp_snapshot_mfnr \
    libchromatix_lavender_ov13855_ofilm_i_cpp_us_chromatix \
    libchromatix_lavender_ov13855_ofilm_i_cpp_video \
    libchromatix_lavender_ov13855_ofilm_i_cpp_video_face \
    libchromatix_lavender_ov13855_ofilm_i_cpp_video_full \
    libchromatix_lavender_ov13855_ofilm_i_cpp_video_weixin \
    libchromatix_lavender_ov13855_ofilm_i_cpp_video_weixin_res1 \
    libchromatix_lavender_ov13855_ofilm_i_default_preview_bu64297 \
    libchromatix_lavender_ov13855_ofilm_i_default_video \
    libchromatix_lavender_ov13855_ofilm_i_default_video_bu64297 \
    libchromatix_lavender_ov13855_ofilm_i_default_video_bu64297_douyin \
    libchromatix_lavender_ov13855_ofilm_i_face_video_3a \
    libchromatix_lavender_ov13855_ofilm_i_flash_cpp_liveshot \
    libchromatix_lavender_ov13855_ofilm_i_flash_cpp_preview \
    libchromatix_lavender_ov13855_ofilm_i_flash_cpp_snapshot \
    libchromatix_lavender_ov13855_ofilm_i_flash_cpp_video \
    libchromatix_lavender_ov13855_ofilm_i_flash_preview \
    libchromatix_lavender_ov13855_ofilm_i_flash_preview_3a \
    libchromatix_lavender_ov13855_ofilm_i_flash_snapshot \
    libchromatix_lavender_ov13855_ofilm_i_flash_video \
    libchromatix_lavender_ov13855_ofilm_i_flash_video_3a \
    libchromatix_lavender_ov13855_ofilm_i_hfr_120 \
    libchromatix_lavender_ov13855_ofilm_i_hfr_120_bu64297 \
    libchromatix_lavender_ov13855_ofilm_i_hfr_60 \
    libchromatix_lavender_ov13855_ofilm_i_hfr_60_bu64297 \
    libchromatix_lavender_ov13855_ofilm_i_hfr_90 \
    libchromatix_lavender_ov13855_ofilm_i_hfr_90_bu64297 \
    libchromatix_lavender_ov13855_ofilm_i_liveshot \
    libchromatix_lavender_ov13855_ofilm_i_postproc \
    libchromatix_lavender_ov13855_ofilm_i_preview \
    libchromatix_lavender_ov13855_ofilm_i_snapshot \
    libchromatix_lavender_ov13855_ofilm_i_snapshot_hdr \
    libchromatix_lavender_ov13855_ofilm_i_video_face \
    libchromatix_lavender_ov13855_ofilm_i_video_full \
    libchromatix_lavender_ov13855_ofilm_i_video_weixin \
    libchromatix_lavender_ov13855_ofilm_i_video_weixin_res1 \
    libchromatix_lavender_ov13855_ofilm_i_weixin_video_3a \
    libchromatix_lavender_ov13855_ofilm_i_weixin_video_3a_res1 \
    libchromatix_lavender_ov13855_ofilm_i_zsl_preview_bu64297 \
    libchromatix_lavender_ov13855_ofilm_i_zsl_video_bu64297 \
    libchromatix_lavender_ov13855_ofilm_india_i_common \
    libchromatix_lavender_ov13855_ofilm_india_i_cpp_ds_chromatix \
    libchromatix_lavender_ov13855_ofilm_india_i_cpp_hfr_120 \
    libchromatix_lavender_ov13855_ofilm_india_i_cpp_hfr_60 \
    libchromatix_lavender_ov13855_ofilm_india_i_cpp_hfr_90 \
    libchromatix_lavender_ov13855_ofilm_india_i_cpp_liveshot \
    libchromatix_lavender_ov13855_ofilm_india_i_cpp_preview \
    libchromatix_lavender_ov13855_ofilm_india_i_cpp_preview_video \
    libchromatix_lavender_ov13855_ofilm_india_i_cpp_snapshot \
    libchromatix_lavender_ov13855_ofilm_india_i_cpp_snapshot_hdr \
    libchromatix_lavender_ov13855_ofilm_india_i_cpp_snapshot_mfnr \
    libchromatix_lavender_ov13855_ofilm_india_i_cpp_us_chromatix \
    libchromatix_lavender_ov13855_ofilm_india_i_cpp_video \
    libchromatix_lavender_ov13855_ofilm_india_i_cpp_video_face \
    libchromatix_lavender_ov13855_ofilm_india_i_cpp_video_full \
    libchromatix_lavender_ov13855_ofilm_india_i_cpp_video_weixin \
    libchromatix_lavender_ov13855_ofilm_india_i_cpp_video_weixin_res1 \
    libchromatix_lavender_ov13855_ofilm_india_i_default_preview_bu64297 \
    libchromatix_lavender_ov13855_ofilm_india_i_default_video \
    libchromatix_lavender_ov13855_ofilm_india_i_default_video_bu64297 \
    libchromatix_lavender_ov13855_ofilm_india_i_face_video_3a \
    libchromatix_lavender_ov13855_ofilm_india_i_flash_cpp_liveshot \
    libchromatix_lavender_ov13855_ofilm_india_i_flash_cpp_preview \
    libchromatix_lavender_ov13855_ofilm_india_i_flash_cpp_snapshot \
    libchromatix_lavender_ov13855_ofilm_india_i_flash_cpp_video \
    libchromatix_lavender_ov13855_ofilm_india_i_flash_preview \
    libchromatix_lavender_ov13855_ofilm_india_i_flash_preview_3a \
    libchromatix_lavender_ov13855_ofilm_india_i_flash_snapshot \
    libchromatix_lavender_ov13855_ofilm_india_i_flash_video \
    libchromatix_lavender_ov13855_ofilm_india_i_flash_video_3a \
    libchromatix_lavender_ov13855_ofilm_india_i_hfr_120 \
    libchromatix_lavender_ov13855_ofilm_india_i_hfr_120_bu64297 \
    libchromatix_lavender_ov13855_ofilm_india_i_hfr_60 \
    libchromatix_lavender_ov13855_ofilm_india_i_hfr_60_bu64297 \
    libchromatix_lavender_ov13855_ofilm_india_i_hfr_90 \
    libchromatix_lavender_ov13855_ofilm_india_i_hfr_90_bu64297 \
    libchromatix_lavender_ov13855_ofilm_india_i_liveshot \
    libchromatix_lavender_ov13855_ofilm_india_i_postproc \
    libchromatix_lavender_ov13855_ofilm_india_i_preview \
    libchromatix_lavender_ov13855_ofilm_india_i_snapshot \
    libchromatix_lavender_ov13855_ofilm_india_i_snapshot_hdr \
    libchromatix_lavender_ov13855_ofilm_india_i_video_face \
    libchromatix_lavender_ov13855_ofilm_india_i_video_full \
    libchromatix_lavender_ov13855_ofilm_india_i_video_weixin \
    libchromatix_lavender_ov13855_ofilm_india_i_video_weixin_res1 \
    libchromatix_lavender_ov13855_ofilm_india_i_weixin_video_3a \
    libchromatix_lavender_ov13855_ofilm_india_i_weixin_video_3a_res1 \
    libchromatix_lavender_ov13855_ofilm_india_i_zsl_preview_bu64297 \
    libchromatix_lavender_ov13855_ofilm_india_i_zsl_video_bu64297 \
    libchromatix_lavender_ov13855_sunny_global_ii_common \
    libchromatix_lavender_ov13855_sunny_global_ii_cpp_ds_chromatix \
    libchromatix_lavender_ov13855_sunny_global_ii_cpp_hfr_120 \
    libchromatix_lavender_ov13855_sunny_global_ii_cpp_hfr_60 \
    libchromatix_lavender_ov13855_sunny_global_ii_cpp_hfr_90 \
    libchromatix_lavender_ov13855_sunny_global_ii_cpp_liveshot \
    libchromatix_lavender_ov13855_sunny_global_ii_cpp_preview \
    libchromatix_lavender_ov13855_sunny_global_ii_cpp_preview_video \
    libchromatix_lavender_ov13855_sunny_global_ii_cpp_snapshot \
    libchromatix_lavender_ov13855_sunny_global_ii_cpp_snapshot_hdr \
    libchromatix_lavender_ov13855_sunny_global_ii_cpp_snapshot_mfnr \
    libchromatix_lavender_ov13855_sunny_global_ii_cpp_us_chromatix \
    libchromatix_lavender_ov13855_sunny_global_ii_cpp_video \
    libchromatix_lavender_ov13855_sunny_global_ii_cpp_video_face \
    libchromatix_lavender_ov13855_sunny_global_ii_cpp_video_full \
    libchromatix_lavender_ov13855_sunny_global_ii_cpp_video_weixin \
    libchromatix_lavender_ov13855_sunny_global_ii_cpp_video_weixin_res1 \
    libchromatix_lavender_ov13855_sunny_global_ii_default_preview_bu64297 \
    libchromatix_lavender_ov13855_sunny_global_ii_default_video \
    libchromatix_lavender_ov13855_sunny_global_ii_default_video_bu64297 \
    libchromatix_lavender_ov13855_sunny_global_ii_default_video_bu64297_douyin \
    libchromatix_lavender_ov13855_sunny_global_ii_face_video_3a \
    libchromatix_lavender_ov13855_sunny_global_ii_flash_cpp_liveshot \
    libchromatix_lavender_ov13855_sunny_global_ii_flash_cpp_preview \
    libchromatix_lavender_ov13855_sunny_global_ii_flash_cpp_snapshot \
    libchromatix_lavender_ov13855_sunny_global_ii_flash_cpp_video \
    libchromatix_lavender_ov13855_sunny_global_ii_flash_preview \
    libchromatix_lavender_ov13855_sunny_global_ii_flash_preview_3a \
    libchromatix_lavender_ov13855_sunny_global_ii_flash_snapshot \
    libchromatix_lavender_ov13855_sunny_global_ii_flash_video \
    libchromatix_lavender_ov13855_sunny_global_ii_flash_video_3a \
    libchromatix_lavender_ov13855_sunny_global_ii_hfr_120 \
    libchromatix_lavender_ov13855_sunny_global_ii_hfr_120_bu64297 \
    libchromatix_lavender_ov13855_sunny_global_ii_hfr_60 \
    libchromatix_lavender_ov13855_sunny_global_ii_hfr_60_bu64297 \
    libchromatix_lavender_ov13855_sunny_global_ii_hfr_90 \
    libchromatix_lavender_ov13855_sunny_global_ii_hfr_90_bu64297 \
    libchromatix_lavender_ov13855_sunny_global_ii_liveshot \
    libchromatix_lavender_ov13855_sunny_global_ii_postproc \
    libchromatix_lavender_ov13855_sunny_global_ii_preview \
    libchromatix_lavender_ov13855_sunny_global_ii_snapshot \
    libchromatix_lavender_ov13855_sunny_global_ii_snapshot_hdr \
    libchromatix_lavender_ov13855_sunny_global_ii_video_face \
    libchromatix_lavender_ov13855_sunny_global_ii_video_full \
    libchromatix_lavender_ov13855_sunny_global_ii_video_weixin \
    libchromatix_lavender_ov13855_sunny_global_ii_video_weixin_res1 \
    libchromatix_lavender_ov13855_sunny_global_ii_weixin_video_3a \
    libchromatix_lavender_ov13855_sunny_global_ii_weixin_video_3a_res1 \
    libchromatix_lavender_ov13855_sunny_global_ii_zsl_preview_bu64297 \
    libchromatix_lavender_ov13855_sunny_global_ii_zsl_video_bu64297 \
    libchromatix_lavender_ov13855_sunny_ii_common \
    libchromatix_lavender_ov13855_sunny_ii_cpp_ds_chromatix \
    libchromatix_lavender_ov13855_sunny_ii_cpp_hfr_120 \
    libchromatix_lavender_ov13855_sunny_ii_cpp_hfr_60 \
    libchromatix_lavender_ov13855_sunny_ii_cpp_hfr_90 \
    libchromatix_lavender_ov13855_sunny_ii_cpp_liveshot \
    libchromatix_lavender_ov13855_sunny_ii_cpp_preview \
    libchromatix_lavender_ov13855_sunny_ii_cpp_preview_video \
    libchromatix_lavender_ov13855_sunny_ii_cpp_snapshot \
    libchromatix_lavender_ov13855_sunny_ii_cpp_snapshot_hdr \
    libchromatix_lavender_ov13855_sunny_ii_cpp_snapshot_mfnr \
    libchromatix_lavender_ov13855_sunny_ii_cpp_us_chromatix \
    libchromatix_lavender_ov13855_sunny_ii_cpp_video \
    libchromatix_lavender_ov13855_sunny_ii_cpp_video_face \
    libchromatix_lavender_ov13855_sunny_ii_cpp_video_full \
    libchromatix_lavender_ov13855_sunny_ii_cpp_video_weixin \
    libchromatix_lavender_ov13855_sunny_ii_cpp_video_weixin_res1 \
    libchromatix_lavender_ov13855_sunny_ii_default_preview_bu64297 \
    libchromatix_lavender_ov13855_sunny_ii_default_video \
    libchromatix_lavender_ov13855_sunny_ii_default_video_bu64297 \
    libchromatix_lavender_ov13855_sunny_ii_default_video_bu64297_douyin \
    libchromatix_lavender_ov13855_sunny_ii_face_video_3a \
    libchromatix_lavender_ov13855_sunny_ii_flash_cpp_liveshot \
    libchromatix_lavender_ov13855_sunny_ii_flash_cpp_preview \
    libchromatix_lavender_ov13855_sunny_ii_flash_cpp_snapshot \
    libchromatix_lavender_ov13855_sunny_ii_flash_cpp_video \
    libchromatix_lavender_ov13855_sunny_ii_flash_preview \
    libchromatix_lavender_ov13855_sunny_ii_flash_preview_3a \
    libchromatix_lavender_ov13855_sunny_ii_flash_snapshot \
    libchromatix_lavender_ov13855_sunny_ii_flash_video \
    libchromatix_lavender_ov13855_sunny_ii_flash_video_3a \
    libchromatix_lavender_ov13855_sunny_ii_hfr_120 \
    libchromatix_lavender_ov13855_sunny_ii_hfr_120_bu64297 \
    libchromatix_lavender_ov13855_sunny_ii_hfr_60 \
    libchromatix_lavender_ov13855_sunny_ii_hfr_60_bu64297 \
    libchromatix_lavender_ov13855_sunny_ii_hfr_90 \
    libchromatix_lavender_ov13855_sunny_ii_hfr_90_bu64297 \
    libchromatix_lavender_ov13855_sunny_ii_liveshot \
    libchromatix_lavender_ov13855_sunny_ii_postproc \
    libchromatix_lavender_ov13855_sunny_ii_preview \
    libchromatix_lavender_ov13855_sunny_ii_snapshot \
    libchromatix_lavender_ov13855_sunny_ii_snapshot_hdr \
    libchromatix_lavender_ov13855_sunny_ii_video_face \
    libchromatix_lavender_ov13855_sunny_ii_video_full \
    libchromatix_lavender_ov13855_sunny_ii_video_weixin \
    libchromatix_lavender_ov13855_sunny_ii_video_weixin_res1 \
    libchromatix_lavender_ov13855_sunny_ii_weixin_video_3a \
    libchromatix_lavender_ov13855_sunny_ii_weixin_video_3a_res1 \
    libchromatix_lavender_ov13855_sunny_ii_zsl_preview_bu64297 \
    libchromatix_lavender_ov13855_sunny_ii_zsl_video_bu64297 \
    libchromatix_lavender_ov13855_sunny_india_ii_common \
    libchromatix_lavender_ov13855_sunny_india_ii_cpp_ds_chromatix \
    libchromatix_lavender_ov13855_sunny_india_ii_cpp_hfr_120 \
    libchromatix_lavender_ov13855_sunny_india_ii_cpp_hfr_60 \
    libchromatix_lavender_ov13855_sunny_india_ii_cpp_hfr_90 \
    libchromatix_lavender_ov13855_sunny_india_ii_cpp_liveshot \
    libchromatix_lavender_ov13855_sunny_india_ii_cpp_preview \
    libchromatix_lavender_ov13855_sunny_india_ii_cpp_preview_video \
    libchromatix_lavender_ov13855_sunny_india_ii_cpp_snapshot \
    libchromatix_lavender_ov13855_sunny_india_ii_cpp_snapshot_hdr \
    libchromatix_lavender_ov13855_sunny_india_ii_cpp_snapshot_mfnr \
    libchromatix_lavender_ov13855_sunny_india_ii_cpp_us_chromatix \
    libchromatix_lavender_ov13855_sunny_india_ii_cpp_video \
    libchromatix_lavender_ov13855_sunny_india_ii_cpp_video_face \
    libchromatix_lavender_ov13855_sunny_india_ii_cpp_video_full \
    libchromatix_lavender_ov13855_sunny_india_ii_cpp_video_weixin \
    libchromatix_lavender_ov13855_sunny_india_ii_cpp_video_weixin_res1 \
    libchromatix_lavender_ov13855_sunny_india_ii_default_preview_bu64297 \
    libchromatix_lavender_ov13855_sunny_india_ii_default_video \
    libchromatix_lavender_ov13855_sunny_india_ii_default_video_bu64297 \
    libchromatix_lavender_ov13855_sunny_india_ii_face_video_3a \
    libchromatix_lavender_ov13855_sunny_india_ii_flash_cpp_liveshot \
    libchromatix_lavender_ov13855_sunny_india_ii_flash_cpp_preview \
    libchromatix_lavender_ov13855_sunny_india_ii_flash_cpp_snapshot \
    libchromatix_lavender_ov13855_sunny_india_ii_flash_cpp_video \
    libchromatix_lavender_ov13855_sunny_india_ii_flash_preview \
    libchromatix_lavender_ov13855_sunny_india_ii_flash_preview_3a \
    libchromatix_lavender_ov13855_sunny_india_ii_flash_snapshot \
    libchromatix_lavender_ov13855_sunny_india_ii_flash_video \
    libchromatix_lavender_ov13855_sunny_india_ii_flash_video_3a \
    libchromatix_lavender_ov13855_sunny_india_ii_hfr_120 \
    libchromatix_lavender_ov13855_sunny_india_ii_hfr_120_bu64297 \
    libchromatix_lavender_ov13855_sunny_india_ii_hfr_60 \
    libchromatix_lavender_ov13855_sunny_india_ii_hfr_60_bu64297 \
    libchromatix_lavender_ov13855_sunny_india_ii_hfr_90 \
    libchromatix_lavender_ov13855_sunny_india_ii_hfr_90_bu64297 \
    libchromatix_lavender_ov13855_sunny_india_ii_liveshot \
    libchromatix_lavender_ov13855_sunny_india_ii_postproc \
    libchromatix_lavender_ov13855_sunny_india_ii_preview \
    libchromatix_lavender_ov13855_sunny_india_ii_snapshot \
    libchromatix_lavender_ov13855_sunny_india_ii_snapshot_hdr \
    libchromatix_lavender_ov13855_sunny_india_ii_video_face \
    libchromatix_lavender_ov13855_sunny_india_ii_video_full \
    libchromatix_lavender_ov13855_sunny_india_ii_video_weixin \
    libchromatix_lavender_ov13855_sunny_india_ii_video_weixin_res1 \
    libchromatix_lavender_ov13855_sunny_india_ii_weixin_video_3a \
    libchromatix_lavender_ov13855_sunny_india_ii_weixin_video_3a_res1 \
    libchromatix_lavender_ov13855_sunny_india_ii_zsl_preview_bu64297 \
    libchromatix_lavender_ov13855_sunny_india_ii_zsl_video_bu64297 \
    libchromatix_lavender_s5k5e8_ofilm_cn_i_a3_default_preview \
    libchromatix_lavender_s5k5e8_ofilm_cn_i_a3_default_video \
    libchromatix_lavender_s5k5e8_ofilm_cn_i_a3_hfr_120 \
    libchromatix_lavender_s5k5e8_ofilm_cn_i_a3_hfr_60 \
    libchromatix_lavender_s5k5e8_ofilm_cn_i_a3_hfr_90 \
    libchromatix_lavender_s5k5e8_ofilm_cn_i_common \
    libchromatix_lavender_s5k5e8_ofilm_cn_i_cpp_ds_chromatix \
    libchromatix_lavender_s5k5e8_ofilm_cn_i_cpp_hfr_120 \
    libchromatix_lavender_s5k5e8_ofilm_cn_i_cpp_hfr_60 \
    libchromatix_lavender_s5k5e8_ofilm_cn_i_cpp_hfr_90 \
    libchromatix_lavender_s5k5e8_ofilm_cn_i_cpp_liveshot \
    libchromatix_lavender_s5k5e8_ofilm_cn_i_cpp_preview \
    libchromatix_lavender_s5k5e8_ofilm_cn_i_cpp_snapshot \
    libchromatix_lavender_s5k5e8_ofilm_cn_i_cpp_us_chromatix \
    libchromatix_lavender_s5k5e8_ofilm_cn_i_cpp_video \
    libchromatix_lavender_s5k5e8_ofilm_cn_i_cpp_video_full \
    libchromatix_lavender_s5k5e8_ofilm_cn_i_default_video \
    libchromatix_lavender_s5k5e8_ofilm_cn_i_hfr_120 \
    libchromatix_lavender_s5k5e8_ofilm_cn_i_hfr_60 \
    libchromatix_lavender_s5k5e8_ofilm_cn_i_hfr_90 \
    libchromatix_lavender_s5k5e8_ofilm_cn_i_liveshot \
    libchromatix_lavender_s5k5e8_ofilm_cn_i_postproc \
    libchromatix_lavender_s5k5e8_ofilm_cn_i_preview \
    libchromatix_lavender_s5k5e8_ofilm_cn_i_snapshot \
    libchromatix_lavender_s5k5e8_ofilm_cn_i_video_full \
    libchromatix_lavender_s5k5e8_ofilm_cn_i_zsl_preview \
    libchromatix_lavender_s5k5e8_ofilm_cn_i_zsl_video \
    libchromatix_lavender_s5k5e8_sunny_cn_ii_a3_default_preview \
    libchromatix_lavender_s5k5e8_sunny_cn_ii_a3_default_video \
    libchromatix_lavender_s5k5e8_sunny_cn_ii_a3_hfr_120 \
    libchromatix_lavender_s5k5e8_sunny_cn_ii_a3_hfr_60 \
    libchromatix_lavender_s5k5e8_sunny_cn_ii_a3_hfr_90 \
    libchromatix_lavender_s5k5e8_sunny_cn_ii_common \
    libchromatix_lavender_s5k5e8_sunny_cn_ii_cpp_ds_chromatix \
    libchromatix_lavender_s5k5e8_sunny_cn_ii_cpp_hfr_120 \
    libchromatix_lavender_s5k5e8_sunny_cn_ii_cpp_hfr_60 \
    libchromatix_lavender_s5k5e8_sunny_cn_ii_cpp_hfr_90 \
    libchromatix_lavender_s5k5e8_sunny_cn_ii_cpp_liveshot \
    libchromatix_lavender_s5k5e8_sunny_cn_ii_cpp_preview \
    libchromatix_lavender_s5k5e8_sunny_cn_ii_cpp_snapshot \
    libchromatix_lavender_s5k5e8_sunny_cn_ii_cpp_us_chromatix \
    libchromatix_lavender_s5k5e8_sunny_cn_ii_cpp_video \
    libchromatix_lavender_s5k5e8_sunny_cn_ii_cpp_video_full \
    libchromatix_lavender_s5k5e8_sunny_cn_ii_default_video \
    libchromatix_lavender_s5k5e8_sunny_cn_ii_hfr_120 \
    libchromatix_lavender_s5k5e8_sunny_cn_ii_hfr_60 \
    libchromatix_lavender_s5k5e8_sunny_cn_ii_hfr_90 \
    libchromatix_lavender_s5k5e8_sunny_cn_ii_liveshot \
    libchromatix_lavender_s5k5e8_sunny_cn_ii_postproc \
    libchromatix_lavender_s5k5e8_sunny_cn_ii_preview \
    libchromatix_lavender_s5k5e8_sunny_cn_ii_snapshot \
    libchromatix_lavender_s5k5e8_sunny_cn_ii_video_full \
    libchromatix_lavender_s5k5e8_sunny_cn_ii_zsl_preview \
    libchromatix_lavender_s5k5e8_sunny_cn_ii_zsl_video \
    libchromatix_lavender_s5kgm1_ofilm_i_4k_preview_3a \
    libchromatix_lavender_s5kgm1_ofilm_i_4k_video_3a \
    libchromatix_lavender_s5kgm1_ofilm_i_bokeh_preview_3a \
    libchromatix_lavender_s5kgm1_ofilm_i_common \
    libchromatix_lavender_s5kgm1_ofilm_i_cpp_hfr_120 \
    libchromatix_lavender_s5kgm1_ofilm_i_cpp_hfr_240 \
    libchromatix_lavender_s5kgm1_ofilm_i_cpp_hfr_60 \
    libchromatix_lavender_s5kgm1_ofilm_i_cpp_hfr_90 \
    libchromatix_lavender_s5kgm1_ofilm_i_cpp_liveshot \
    libchromatix_lavender_s5kgm1_ofilm_i_cpp_preview \
    libchromatix_lavender_s5kgm1_ofilm_i_cpp_preview_sn \
    libchromatix_lavender_s5kgm1_ofilm_i_cpp_preview_sr \
    libchromatix_lavender_s5kgm1_ofilm_i_cpp_preview_video \
    libchromatix_lavender_s5kgm1_ofilm_i_cpp_snapshot \
    libchromatix_lavender_s5kgm1_ofilm_i_cpp_snapshot_bokeh \
    libchromatix_lavender_s5kgm1_ofilm_i_cpp_snapshot_hdr \
    libchromatix_lavender_s5kgm1_ofilm_i_cpp_snapshot_hht \
    libchromatix_lavender_s5kgm1_ofilm_i_cpp_snapshot_sn \
    libchromatix_lavender_s5kgm1_ofilm_i_cpp_snapshot_sr \
    libchromatix_lavender_s5kgm1_ofilm_i_cpp_video \
    libchromatix_lavender_s5kgm1_ofilm_i_cpp_video_4k \
    libchromatix_lavender_s5kgm1_ofilm_i_cpp_video_weixin \
    libchromatix_lavender_s5kgm1_ofilm_i_cpp_video_weixin_res1 \
    libchromatix_lavender_s5kgm1_ofilm_i_default_preview_3a \
    libchromatix_lavender_s5kgm1_ofilm_i_default_video_3a \
    libchromatix_lavender_s5kgm1_ofilm_i_hfr_120 \
    libchromatix_lavender_s5kgm1_ofilm_i_hfr_120_3a \
    libchromatix_lavender_s5kgm1_ofilm_i_hfr_240 \
    libchromatix_lavender_s5kgm1_ofilm_i_hfr_240_3a \
    libchromatix_lavender_s5kgm1_ofilm_i_hfr_60 \
    libchromatix_lavender_s5kgm1_ofilm_i_hfr_60_3a \
    libchromatix_lavender_s5kgm1_ofilm_i_hfr_90 \
    libchromatix_lavender_s5kgm1_ofilm_i_hfr_90_3a \
    libchromatix_lavender_s5kgm1_ofilm_i_pano_preview_3a \
    libchromatix_lavender_s5kgm1_ofilm_i_postproc \
    libchromatix_lavender_s5kgm1_ofilm_i_preview \
    libchromatix_lavender_s5kgm1_ofilm_i_preview_cts \
    libchromatix_lavender_s5kgm1_ofilm_i_snapshot \
    libchromatix_lavender_s5kgm1_ofilm_i_snapshot_bokeh \
    libchromatix_lavender_s5kgm1_ofilm_i_snapshot_hdr \
    libchromatix_lavender_s5kgm1_ofilm_i_snapshot_sn \
    libchromatix_lavender_s5kgm1_ofilm_i_video \
    libchromatix_lavender_s5kgm1_ofilm_i_video_4k \
    libchromatix_lavender_s5kgm1_ofilm_i_video_weixin \
    libchromatix_lavender_s5kgm1_ofilm_i_video_weixin_res1 \
    libchromatix_lavender_s5kgm1_ofilm_i_weixin_video_3a \
    libchromatix_lavender_s5kgm1_ofilm_i_weixin_video_3a_res1 \
    libchromatix_lavender_s5kgm1_ofilm_i_zsl_preview_3a \
    libchromatix_lavender_s5kgm1_ofilm_i_zsl_preview_3a_its \
    libchromatix_lavender_s5kgm1_ofilm_i_zsl_preview_3a_sn \
    libchromatix_lavender_s5kgm1_ofilm_i_zsl_video_3a \
    libchromatix_lavender_s5kgm1_ofilm_india_i_4k_preview_3a \
    libchromatix_lavender_s5kgm1_ofilm_india_i_4k_video_3a \
    libchromatix_lavender_s5kgm1_ofilm_india_i_bokeh_preview_3a \
    libchromatix_lavender_s5kgm1_ofilm_india_i_common \
    libchromatix_lavender_s5kgm1_ofilm_india_i_cpp_hfr_120 \
    libchromatix_lavender_s5kgm1_ofilm_india_i_cpp_hfr_60 \
    libchromatix_lavender_s5kgm1_ofilm_india_i_cpp_hfr_90 \
    libchromatix_lavender_s5kgm1_ofilm_india_i_cpp_liveshot \
    libchromatix_lavender_s5kgm1_ofilm_india_i_cpp_preview \
    libchromatix_lavender_s5kgm1_ofilm_india_i_cpp_preview_sn \
    libchromatix_lavender_s5kgm1_ofilm_india_i_cpp_preview_sr \
    libchromatix_lavender_s5kgm1_ofilm_india_i_cpp_preview_video \
    libchromatix_lavender_s5kgm1_ofilm_india_i_cpp_snapshot \
    libchromatix_lavender_s5kgm1_ofilm_india_i_cpp_snapshot_bokeh \
    libchromatix_lavender_s5kgm1_ofilm_india_i_cpp_snapshot_hdr \
    libchromatix_lavender_s5kgm1_ofilm_india_i_cpp_snapshot_hht \
    libchromatix_lavender_s5kgm1_ofilm_india_i_cpp_snapshot_sn \
    libchromatix_lavender_s5kgm1_ofilm_india_i_cpp_snapshot_sr \
    libchromatix_lavender_s5kgm1_ofilm_india_i_cpp_video \
    libchromatix_lavender_s5kgm1_ofilm_india_i_cpp_video_4k \
    libchromatix_lavender_s5kgm1_ofilm_india_i_cpp_video_weixin \
    libchromatix_lavender_s5kgm1_ofilm_india_i_cpp_video_weixin_res1 \
    libchromatix_lavender_s5kgm1_ofilm_india_i_default_preview_3a \
    libchromatix_lavender_s5kgm1_ofilm_india_i_default_video_3a \
    libchromatix_lavender_s5kgm1_ofilm_india_i_hfr_120 \
    libchromatix_lavender_s5kgm1_ofilm_india_i_hfr_120_3a \
    libchromatix_lavender_s5kgm1_ofilm_india_i_hfr_60 \
    libchromatix_lavender_s5kgm1_ofilm_india_i_hfr_60_3a \
    libchromatix_lavender_s5kgm1_ofilm_india_i_hfr_90 \
    libchromatix_lavender_s5kgm1_ofilm_india_i_hfr_90_3a \
    libchromatix_lavender_s5kgm1_ofilm_india_i_pano_preview_3a \
    libchromatix_lavender_s5kgm1_ofilm_india_i_postproc \
    libchromatix_lavender_s5kgm1_ofilm_india_i_preview \
    libchromatix_lavender_s5kgm1_ofilm_india_i_preview_cts \
    libchromatix_lavender_s5kgm1_ofilm_india_i_snapshot \
    libchromatix_lavender_s5kgm1_ofilm_india_i_snapshot_bokeh \
    libchromatix_lavender_s5kgm1_ofilm_india_i_snapshot_hdr \
    libchromatix_lavender_s5kgm1_ofilm_india_i_snapshot_sn \
    libchromatix_lavender_s5kgm1_ofilm_india_i_video \
    libchromatix_lavender_s5kgm1_ofilm_india_i_video_4k \
    libchromatix_lavender_s5kgm1_ofilm_india_i_video_weixin \
    libchromatix_lavender_s5kgm1_ofilm_india_i_video_weixin_res1 \
    libchromatix_lavender_s5kgm1_ofilm_india_i_weixin_video_3a \
    libchromatix_lavender_s5kgm1_ofilm_india_i_weixin_video_3a_res1 \
    libchromatix_lavender_s5kgm1_ofilm_india_i_zsl_preview_3a \
    libchromatix_lavender_s5kgm1_ofilm_india_i_zsl_preview_3a_its \
    libchromatix_lavender_s5kgm1_ofilm_india_i_zsl_preview_3a_sn \
    libchromatix_lavender_s5kgm1_ofilm_india_i_zsl_video_3a \
    libchromatix_lavender_s5kgm1_sunny_ii_4k_preview_3a \
    libchromatix_lavender_s5kgm1_sunny_ii_4k_video_3a \
    libchromatix_lavender_s5kgm1_sunny_ii_bokeh_preview_3a \
    libchromatix_lavender_s5kgm1_sunny_ii_common \
    libchromatix_lavender_s5kgm1_sunny_ii_cpp_hfr_120 \
    libchromatix_lavender_s5kgm1_sunny_ii_cpp_hfr_240 \
    libchromatix_lavender_s5kgm1_sunny_ii_cpp_hfr_60 \
    libchromatix_lavender_s5kgm1_sunny_ii_cpp_hfr_90 \
    libchromatix_lavender_s5kgm1_sunny_ii_cpp_liveshot \
    libchromatix_lavender_s5kgm1_sunny_ii_cpp_preview \
    libchromatix_lavender_s5kgm1_sunny_ii_cpp_preview_sn \
    libchromatix_lavender_s5kgm1_sunny_ii_cpp_preview_sr \
    libchromatix_lavender_s5kgm1_sunny_ii_cpp_preview_video \
    libchromatix_lavender_s5kgm1_sunny_ii_cpp_snapshot \
    libchromatix_lavender_s5kgm1_sunny_ii_cpp_snapshot_bokeh \
    libchromatix_lavender_s5kgm1_sunny_ii_cpp_snapshot_hdr \
    libchromatix_lavender_s5kgm1_sunny_ii_cpp_snapshot_hht \
    libchromatix_lavender_s5kgm1_sunny_ii_cpp_snapshot_sn \
    libchromatix_lavender_s5kgm1_sunny_ii_cpp_snapshot_sr \
    libchromatix_lavender_s5kgm1_sunny_ii_cpp_video \
    libchromatix_lavender_s5kgm1_sunny_ii_cpp_video_4k \
    libchromatix_lavender_s5kgm1_sunny_ii_cpp_video_weixin \
    libchromatix_lavender_s5kgm1_sunny_ii_cpp_video_weixin_res1 \
    libchromatix_lavender_s5kgm1_sunny_ii_default_preview_3a \
    libchromatix_lavender_s5kgm1_sunny_ii_default_preview_3a_its \
    libchromatix_lavender_s5kgm1_sunny_ii_default_video_3a \
    libchromatix_lavender_s5kgm1_sunny_ii_hfr_120 \
    libchromatix_lavender_s5kgm1_sunny_ii_hfr_120_3a \
    libchromatix_lavender_s5kgm1_sunny_ii_hfr_240 \
    libchromatix_lavender_s5kgm1_sunny_ii_hfr_240_3a \
    libchromatix_lavender_s5kgm1_sunny_ii_hfr_60 \
    libchromatix_lavender_s5kgm1_sunny_ii_hfr_60_3a \
    libchromatix_lavender_s5kgm1_sunny_ii_hfr_90 \
    libchromatix_lavender_s5kgm1_sunny_ii_hfr_90_3a \
    libchromatix_lavender_s5kgm1_sunny_ii_pano_preview_3a \
    libchromatix_lavender_s5kgm1_sunny_ii_postproc \
    libchromatix_lavender_s5kgm1_sunny_ii_preview \
    libchromatix_lavender_s5kgm1_sunny_ii_preview_cts \
    libchromatix_lavender_s5kgm1_sunny_ii_snapshot \
    libchromatix_lavender_s5kgm1_sunny_ii_snapshot_bokeh \
    libchromatix_lavender_s5kgm1_sunny_ii_snapshot_hdr \
    libchromatix_lavender_s5kgm1_sunny_ii_snapshot_its \
    libchromatix_lavender_s5kgm1_sunny_ii_snapshot_sn \
    libchromatix_lavender_s5kgm1_sunny_ii_video \
    libchromatix_lavender_s5kgm1_sunny_ii_video_4k \
    libchromatix_lavender_s5kgm1_sunny_ii_video_weixin \
    libchromatix_lavender_s5kgm1_sunny_ii_video_weixin_res1 \
    libchromatix_lavender_s5kgm1_sunny_ii_weixin_video_3a \
    libchromatix_lavender_s5kgm1_sunny_ii_weixin_video_3a_res1 \
    libchromatix_lavender_s5kgm1_sunny_ii_zsl_preview_3a \
    libchromatix_lavender_s5kgm1_sunny_ii_zsl_preview_3a_its \
    libchromatix_lavender_s5kgm1_sunny_ii_zsl_preview_3a_sn \
    libchromatix_lavender_s5kgm1_sunny_ii_zsl_video_3a \
    libchromatix_lavender_s5kgm1_sunny_india_ii_4k_preview_3a \
    libchromatix_lavender_s5kgm1_sunny_india_ii_4k_video_3a \
    libchromatix_lavender_s5kgm1_sunny_india_ii_bokeh_preview_3a \
    libchromatix_lavender_s5kgm1_sunny_india_ii_common \
    libchromatix_lavender_s5kgm1_sunny_india_ii_cpp_hfr_120 \
    libchromatix_lavender_s5kgm1_sunny_india_ii_cpp_hfr_60 \
    libchromatix_lavender_s5kgm1_sunny_india_ii_cpp_hfr_90 \
    libchromatix_lavender_s5kgm1_sunny_india_ii_cpp_liveshot \
    libchromatix_lavender_s5kgm1_sunny_india_ii_cpp_preview \
    libchromatix_lavender_s5kgm1_sunny_india_ii_cpp_preview_sn \
    libchromatix_lavender_s5kgm1_sunny_india_ii_cpp_preview_sr \
    libchromatix_lavender_s5kgm1_sunny_india_ii_cpp_preview_video \
    libchromatix_lavender_s5kgm1_sunny_india_ii_cpp_snapshot \
    libchromatix_lavender_s5kgm1_sunny_india_ii_cpp_snapshot_bokeh \
    libchromatix_lavender_s5kgm1_sunny_india_ii_cpp_snapshot_hdr \
    libchromatix_lavender_s5kgm1_sunny_india_ii_cpp_snapshot_hht \
    libchromatix_lavender_s5kgm1_sunny_india_ii_cpp_snapshot_sn \
    libchromatix_lavender_s5kgm1_sunny_india_ii_cpp_snapshot_sr \
    libchromatix_lavender_s5kgm1_sunny_india_ii_cpp_video \
    libchromatix_lavender_s5kgm1_sunny_india_ii_cpp_video_4k \
    libchromatix_lavender_s5kgm1_sunny_india_ii_cpp_video_weixin \
    libchromatix_lavender_s5kgm1_sunny_india_ii_cpp_video_weixin_res1 \
    libchromatix_lavender_s5kgm1_sunny_india_ii_default_preview_3a \
    libchromatix_lavender_s5kgm1_sunny_india_ii_default_preview_3a_its \
    libchromatix_lavender_s5kgm1_sunny_india_ii_default_video_3a \
    libchromatix_lavender_s5kgm1_sunny_india_ii_hfr_120 \
    libchromatix_lavender_s5kgm1_sunny_india_ii_hfr_120_3a \
    libchromatix_lavender_s5kgm1_sunny_india_ii_hfr_60 \
    libchromatix_lavender_s5kgm1_sunny_india_ii_hfr_60_3a \
    libchromatix_lavender_s5kgm1_sunny_india_ii_hfr_90 \
    libchromatix_lavender_s5kgm1_sunny_india_ii_hfr_90_3a \
    libchromatix_lavender_s5kgm1_sunny_india_ii_pano_preview_3a \
    libchromatix_lavender_s5kgm1_sunny_india_ii_postproc \
    libchromatix_lavender_s5kgm1_sunny_india_ii_preview \
    libchromatix_lavender_s5kgm1_sunny_india_ii_preview_cts \
    libchromatix_lavender_s5kgm1_sunny_india_ii_snapshot \
    libchromatix_lavender_s5kgm1_sunny_india_ii_snapshot_bokeh \
    libchromatix_lavender_s5kgm1_sunny_india_ii_snapshot_hdr \
    libchromatix_lavender_s5kgm1_sunny_india_ii_snapshot_its \
    libchromatix_lavender_s5kgm1_sunny_india_ii_snapshot_sn \
    libchromatix_lavender_s5kgm1_sunny_india_ii_video \
    libchromatix_lavender_s5kgm1_sunny_india_ii_video_4k \
    libchromatix_lavender_s5kgm1_sunny_india_ii_video_weixin \
    libchromatix_lavender_s5kgm1_sunny_india_ii_video_weixin_res1 \
    libchromatix_lavender_s5kgm1_sunny_india_ii_weixin_video_3a \
    libchromatix_lavender_s5kgm1_sunny_india_ii_weixin_video_3a_res1 \
    libchromatix_lavender_s5kgm1_sunny_india_ii_zsl_preview_3a \
    libchromatix_lavender_s5kgm1_sunny_india_ii_zsl_preview_3a_its \
    libchromatix_lavender_s5kgm1_sunny_india_ii_zsl_preview_3a_sn \
    libchromatix_lavender_s5kgm1_sunny_india_ii_zsl_video_3a \
    libdepthmapwrapper \
    libdrc \
    libflash_pmic \
    libjpegdhw \
    libjpegdmahw \
    libjpegehw \
    libmegface \
    libmibokeh_660 \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_frame_algorithm \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_is \
    libmmcamera2_isp_modules \
    libmmcamera2_mct \
    libmmcamera2_mct_shimlayer \
    libmmcamera2_pp_buf_mgr \
    libmmcamera2_pproc_modules \
    libmmcamera2_q3a_core \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_algorithm \
    libmmcamera2_stats_lib \
    libmmcamera2_stats_modules \
    libmmcamera_arcsoftbokeh_lib \
    libmmcamera_atmel_at24c32e_eeprom \
    libmmcamera_bokeh \
    libmmcamera_depth_map \
    libmmcamera_dummyalgo \
    libmmcamera_eebinparse \
    libmmcamera_eeprom_util \
    libmmcamera_eztune_module \
    libmmcamera_facedetection_lib \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_hdr_gb_lib \
    libmmcamera_hvx_add_constant \
    libmmcamera_hvx_grid_sum \
    libmmcamera_imglib \
    libmmcamera_imglib_faceproc_adspstub \
    libmmcamera_isp_abf48 \
    libmmcamera_isp_aec_bg_stats47 \
    libmmcamera_isp_bf_stats47 \
    libmmcamera_isp_bg_stats46 \
    libmmcamera_isp_bhist_stats44 \
    libmmcamera_isp_black_level48 \
    libmmcamera_isp_bpc48 \
    libmmcamera_isp_cac47 \
    libmmcamera_isp_chroma_enhan40 \
    libmmcamera_isp_chroma_suppress40 \
    libmmcamera_isp_clamp_encoder40 \
    libmmcamera_isp_clamp_video40 \
    libmmcamera_isp_clamp_viewfinder40 \
    libmmcamera_isp_color_correct46 \
    libmmcamera_isp_color_xform_encoder46 \
    libmmcamera_isp_color_xform_video46 \
    libmmcamera_isp_color_xform_viewfinder46 \
    libmmcamera_isp_cs_stats46 \
    libmmcamera_isp_demosaic48 \
    libmmcamera_isp_demux48 \
    libmmcamera_isp_fovcrop_encoder46 \
    libmmcamera_isp_fovcrop_video46 \
    libmmcamera_isp_fovcrop_viewfinder46 \
    libmmcamera_isp_gamma44 \
    libmmcamera_isp_gic48 \
    libmmcamera_isp_gtm46 \
    libmmcamera_isp_hdr48 \
    libmmcamera_isp_hdr_be_stats46 \
    libmmcamera_isp_hdr_bhist_stats44 \
    libmmcamera_isp_ihist_stats46 \
    libmmcamera_isp_linearization40 \
    libmmcamera_isp_ltm47 \
    libmmcamera_isp_luma_adaptation40 \
    libmmcamera_isp_mce40 \
    libmmcamera_isp_mesh_rolloff44 \
    libmmcamera_isp_pdaf48 \
    libmmcamera_isp_pedestal_correct46 \
    libmmcamera_isp_rs_stats46 \
    libmmcamera_isp_scaler_encoder46 \
    libmmcamera_isp_scaler_video46 \
    libmmcamera_isp_scaler_viewfinder46 \
    libmmcamera_isp_sce40 \
    libmmcamera_isp_snr47 \
    libmmcamera_isp_sub_module \
    libmmcamera_lavender_imx486_ofilm_i \
    libmmcamera_lavender_imx486_ofilm_i_dw9714 \
    libmmcamera_lavender_imx486_ofilm_i_dw9714_eeprom \
    libmmcamera_lavender_imx486_ofilm_i_eeprom \
    libmmcamera_lavender_ov02a10_ofilm_i \
    libmmcamera_lavender_ov02a10_ofilm_i_eeprom \
    libmmcamera_lavender_ov02a10_sunny_ii \
    libmmcamera_lavender_ov02a10_sunny_ii_eeprom \
    libmmcamera_lavender_ov12a10_sunny_ii \
    libmmcamera_lavender_ov12a10_sunny_ii_eeprom \
    libmmcamera_lavender_ov13855_ofilm_i \
    libmmcamera_lavender_ov13855_ofilm_i_eeprom \
    libmmcamera_lavender_ov13855_sunny_ii \
    libmmcamera_lavender_ov13855_sunny_ii_eeprom \
    libmmcamera_lavender_s5k5e8_ofilm_i \
    libmmcamera_lavender_s5k5e8_ofilm_i_eeprom \
    libmmcamera_lavender_s5k5e8_sunny_ii \
    libmmcamera_lavender_s5k5e8_sunny_ii_eeprom \
    libmmcamera_lavender_s5kgm1_ofilm_i \
    libmmcamera_lavender_s5kgm1_sunny_ii \
    libmmcamera_lavender_s5kgm1sp_ofilm_i_eeprom \
    libmmcamera_lavender_s5kgm1sp_sunny_ii_eeprom \
    libmmcamera_le2464c_eeprom \
    libmmcamera_le2464c_master_eeprom \
    libmmcamera_mg_facepp_lib \
    libmmcamera_paaf_lib \
    libmmcamera_pdaf \
    libmmcamera_pdafcamif \
    libmmcamera_ppbase_module \
    libmmcamera_ppeiscore \
    libmmcamera_quadracfa \
    libmmcamera_rohm_brcg064gwz_3_eeprom \
    libmmcamera_sunny_ov13855_eeprom \
    libmmcamera_sw2d_lib \
    libmmcamera_thread_services \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libmmjpeg \
    libmmqjpeg_codec \
    libmmqjpegdma \
    libmpbase \
    libois_bu63165 \
    libois_lc898122 \
    libqomx_jpegdec \
    libqomx_jpegenc \
    libqomx_jpegenc_pipe \
    libremosaic_daemon \
    libsmwrapper \
    libsurround_3mic_proc \
    libsymphony-cpu \
    libsymphonypower \
    libts_detected_face_hal \
    libts_face_beautify_hal \
    libvideoutils \
    libvidhance \
    libvidhance_gyro \
    libdirac \
    libmisoundfx \
    com.qualcomm.qti.imscmservice@2.0 \
    com.qualcomm.qti.imscmservice@2.1 \
    com.qualcomm.qti.imscmservice@2.2 \
    com.qualcomm.qti.uceservice@2.0 \
    com.qualcomm.qti.uceservice@2.1 \
    com.qualcomm.qti.uceservice@2.2 \
    com.qualcomm.qti.uceservice@2.3 \
    com.dsi.ant@1.0-impl \
    consumerir.lirc.sdm660 \
    consumerir.spi.sdm660 \
    fingerprint.fpc.default \
    fingerprint.goodix.default \
    vendor.qti.gnss@4.3-impl \
    vendor.qti.hardware.alarm@1.0-impl \
    vendor.qti.hardware.capabilityconfigstore@1.0-impl \
    vendor.qti.hardware.fm@1.0-impl \
    vendor.qti.hardware.soter@1.0-impl \
    lib-imscmservice \
    lib-imsdpl \
    lib-imsqimf \
    lib-imsrcs-v2 \
    lib-imsrcsbaseimpl \
    lib-imsvtcore \
    lib-imsxml \
    lib-rcsconfig \
    lib-rtpcommon \
    lib-rtpcore \
    lib-rtpsl \
    lib-siputility \
    lib-uceservice \
    libGPQTEEC_vendor \
    libGPTEE_vendor \
    libGPreqcancel \
    libSecureUILib \
    libStDrvInt \
    libaoa \
    libbase64 \
    libcdfw \
    libcdfw_remote_api \
    libcne \
    libcneapiclient \
    libcneoplookup \
    libcneqmiutils \
    libconfigdb \
    libdataitems \
    libdisp-aba \
    libdpmqmihal \
    libdrmfs \
    libdrmtime \
    libdsi_netctrl \
    libgarden \
    libgarden_haltests_e2e \
    libgdtap \
    libgf_ca \
    libgf_hal \
    libgnsspps \
    libgoodixhwfingerprint \
    libhdcpsrm \
    libizat_client_api \
    libizat_core \
    liblbs_core \
    libloadalgo_stub \
    libloc_api_v02 \
    libloc_api_wds \
    libloc_qwes_iface \
    libloc_ril_client \
    libloc_socket \
    liblocationservice \
    liblocationservice_glue \
    liblowi_client \
    liblowi_wifihal \
    liblqe \
    libminksocket \
    libmlipay \
    libmlipay@1.1 \
    libnetmgr \
    libnetmgr_common \
    libnetmgr_nr_fusion \
    libnetmgr_rmnet_ext \
    libnlnetmgr \
    liboemaids_vendor \
    liboemcrypto \
    libops \
    libpdmapper \
    libpdnotifier \
    libperipheral_client \
    libqcc_file_agent \
    libqcmaputils \
    libqcrilFramework \
    libqcrildatactl \
    libqisl \
    libqsocket \
    librcc \
    libril-qc-hal-qmi \
    libril-qc-logger \
    libril-qc-ltedirectdisc \
    libril-qc-radioconfig \
    libril-qcril-hook-oem \
    librilqmiservices \
    librmp \
    librpmb \
    libsecureui \
    libsecureui_svcsock \
    libsettings \
    libsi \
    libslimclient \
    libspl \
    libssd \
    libsubsystem_control \
    libsystem_health_mon \
    libtrustedapploader \
    libtzdrmgenprov \
    libvendor.goodix.hardware.interfaces.biometrics.fingerprint@2.1 \
    libwms \
    libwqe \
    libwvhidl \
    libxml \
    libxtadapter \
    libwvdrmengine \
    qcrilHalMarshal \
    qcrild_librilutils \
    qtibus \
    qtimutex \
    vendor.qti.data.factory@2.0_vendor \
    vendor.qti.data.factory@2.1_vendor \
    vendor.qti.data.factory@2.2_vendor \
    vendor.qti.data.factory@2.3_vendor \
    vendor.qti.data.mwqem@1.0_vendor \
    vendor.qti.data.slm@1.0_vendor \
    vendor.qti.gnss@1.0 \
    vendor.qti.gnss@1.1 \
    vendor.qti.gnss@1.2 \
    vendor.qti.gnss@2.0 \
    vendor.qti.gnss@2.1 \
    vendor.qti.gnss@3.0 \
    vendor.qti.gnss@4.0 \
    vendor.qti.gnss@4.1 \
    vendor.qti.gnss@4.2 \
    vendor.qti.gnss@4.3-service \
    vendor.qti.gnss@4.3 \
    vendor.qti.hardware.alarm@1.0_vendor \
    vendor.qti.hardware.data.cne.internal.api@1.0_vendor \
    vendor.qti.hardware.data.cne.internal.constants@1.0_vendor \
    vendor.qti.hardware.data.cne.internal.server@1.0_vendor \
    vendor.qti.hardware.data.connection@1.0_vendor \
    vendor.qti.hardware.data.connection@1.1_vendor \
    vendor.qti.hardware.data.dynamicdds@1.0_vendor \
    vendor.qti.hardware.data.dynamicdds@1.1_vendor \
    vendor.qti.hardware.data.flow@1.0_vendor \
    vendor.qti.hardware.data.iwlan@1.0_vendor \
    vendor.qti.hardware.data.latency@1.0_vendor \
    vendor.qti.hardware.data.lce@1.0_vendor \
    vendor.qti.hardware.data.qmi@1.0_vendor \
    vendor.qti.hardware.fingerprint@1.0 \
    vendor.qti.hardware.qccsyshal@1.0 \
    vendor.qti.hardware.radio.am@1.0_vendor \
    vendor.qti.hardware.radio.ims@1.0 \
    vendor.qti.hardware.radio.ims@1.1 \
    vendor.qti.hardware.radio.ims@1.2 \
    vendor.qti.hardware.radio.ims@1.3 \
    vendor.qti.hardware.radio.ims@1.4 \
    vendor.qti.hardware.radio.ims@1.5 \
    vendor.qti.hardware.radio.ims@1.6 \
    vendor.qti.hardware.radio.ims@1.7 \
    vendor.qti.hardware.radio.internal.deviceinfo@1.0 \
    vendor.qti.hardware.radio.lpa@1.0_vendor \
    vendor.qti.hardware.radio.lpa@1.1_vendor \
    vendor.qti.hardware.radio.lpa@1.2_vendor \
    vendor.qti.hardware.radio.qcrilhook@1.0 \
    vendor.qti.hardware.radio.qtiradio@1.0_vendor \
    vendor.qti.hardware.radio.qtiradio@2.0_vendor \
    vendor.qti.hardware.radio.qtiradio@2.1_vendor \
    vendor.qti.hardware.radio.qtiradio@2.2_vendor \
    vendor.qti.hardware.radio.qtiradio@2.3_vendor \
    vendor.qti.hardware.radio.qtiradio@2.4_vendor \
    vendor.qti.hardware.radio.qtiradio@2.5_vendor \
    vendor.qti.hardware.radio.qtiradio@2.6_vendor \
    vendor.qti.hardware.radio.qtiradio@2.7_vendor \
    vendor.qti.hardware.radio.uim@1.0_vendor \
    vendor.qti.hardware.radio.uim@1.1_vendor \
    vendor.qti.hardware.radio.uim@1.2_vendor \
    vendor.qti.hardware.radio.uim_remote_client@1.0_vendor \
    vendor.qti.hardware.radio.uim_remote_client@1.1_vendor \
    vendor.qti.hardware.radio.uim_remote_client@1.2_vendor \
    vendor.qti.hardware.radio.uim_remote_server@1.0_vendor \
    vendor.qti.hardware.slmadapter@1.0_vendor \
    vendor.qti.hardware.soter@1.0 \
    vendor.qti.ims.callcapability@1.0 \
    vendor.qti.ims.callinfo@1.0 \
    vendor.qti.ims.factory@1.0 \
    vendor.qti.ims.factory@1.1 \
    vendor.qti.ims.rcsconfig@1.0 \
    vendor.qti.ims.rcsconfig@1.1 \
    vendor.qti.ims.rcsconfig@2.0 \
    vendor.qti.ims.rcsconfig@2.1 \
    vendor.qti.imsrtpservice@3.0-service-Impl \
    vendor.qti.imsrtpservice@3.0_vendor \
    vendor.qti.latency@2.0_vendor \
    vendor.qti.latency@2.1_vendor \
    vendor_lib_rfsa_adsp_dirac_resource_dar \
    vendor_lib_rfsa_adsp_libFastRPC_AUE_Forward_skel_so \
    vendor_lib_rfsa_adsp_libFastRPC_UTF_Forward_800h_skel_so \
    vendor_lib_rfsa_adsp_libFastRPC_UTF_Forward_Qtc2_skel_so \
    vendor_lib_rfsa_adsp_libadsp_fd_skel_so \
    vendor_lib_rfsa_adsp_libadsp_hvx_add_constant_so \
    vendor_lib_rfsa_adsp_libadsp_hvx_skel_so \
    vendor_lib_rfsa_adsp_libapps_mem_heap_so \
    vendor_lib_rfsa_adsp_libdirac-capiv2_so \
    vendor_lib_rfsa_adsp_libdspCV_skel_so \
    vendor_lib_rfsa_adsp_libfastcvadsp_so \
    vendor_lib_rfsa_adsp_libfastcvadsp_skel_so \
    vendor_lib_rfsa_adsp_libscveObjectSegmentation_skel_so \
    vendor_lib_rfsa_adsp_libscveT2T_skel_so \
    vendor_lib_rfsa_adsp_libvpp_svc_skel_so \
    vendor_lib_rfsa_adsp_nuance_scd \
    com.qualcomm.qti.ant@1.0 \
    libmmparserextractor \
    libbinauralrenderer_wrapper.qti \
    libhoaeffects.qti \
    libhoaeffects_csim \
    liblistenjni.qti \
    liblistensoundmodel2.qti \
    liblsmclient \
    libmmosal \
    libmmparser_lite \
    libvr_amb_engine \
    libvr_object_engine \
    vendor.qti.hardware.ListenSoundModel@1.0 \
    vendor.qti.hardware.qseecom@1.0 \
    vendor.qti.hardware.sensorscalibrate@1.0 \
    vendor.qti.hardware.tui_comm@1.0 \
    com.qualcomm.qti.dpm.api@1.0 \
    com.quicinc.cne.api@1.0 \
    com.quicinc.cne.api@1.1 \
    com.quicinc.cne.constants@1.0 \
    com.quicinc.cne.constants@2.0 \
    com.quicinc.cne.constants@2.1 \
    com.quicinc.cne.server@1.0 \
    com.quicinc.cne.server@2.0 \
    com.quicinc.cne.server@2.1 \
    com.quicinc.cne.server@2.2 \
    lib-imsvideocodec \
    lib-imsvt \
    lib-imsvtextutils \
    lib-imsvtutils \
    libdiag_system \
    libdpmctmgr \
    libdpmfdmgr \
    libdpmframework \
    libdpmtcm \
    libembmsmmosal \
    libembmsmmparser_lite \
    libembmstinyxml \
    libimscamera_jni \
    libimsmedia_jni \
    libmwqemiptablemgr \
    libqmi_cci_system \
    libqmi_encdec_system \
    libqxrsplitauxservice.qti \
    libsd_sdk_display.qti \
    libsdm-disp-apis.qti \
    vendor.display.color@1.0_system_ext \
    vendor.display.color@1.1_system_ext \
    vendor.display.color@1.2_system_ext \
    vendor.display.postproc@1.0_system_ext \
    vendor.qti.data.factory@1.0 \
    vendor.qti.data.factory@2.0 \
    vendor.qti.data.factory@2.1 \
    vendor.qti.data.factory@2.2 \
    vendor.qti.data.factory@2.3 \
    vendor.qti.data.factory@2.4 \
    vendor.qti.data.factory@2.5 \
    vendor.qti.data.factory@2.6 \
    vendor.qti.data.factory@2.7 \
    vendor.qti.data.factory@2.8 \
    vendor.qti.data.factoryservice-V1-ndk \
    vendor.qti.data.mwqem@1.0 \
    vendor.qti.data.mwqemaidlservice-V1-ndk \
    vendor.qti.data.slm@1.0 \
    vendor.qti.diaghal@1.0 \
    vendor.qti.hardware.alarm@1.0 \
    vendor.qti.hardware.cacertaidlservice-V1-ndk \
    vendor.qti.hardware.data.cne.internal.api@1.0 \
    vendor.qti.hardware.data.cne.internal.constants@1.0 \
    vendor.qti.hardware.data.cne.internal.server@1.0 \
    vendor.qti.hardware.data.cne.internal.server@1.1 \
    vendor.qti.hardware.data.cne.internal.server@1.2 \
    vendor.qti.hardware.data.cne.internal.server@1.3 \
    vendor.qti.hardware.data.cneaidlservice.internal.api-V1-ndk \
    vendor.qti.hardware.data.cneaidlservice.internal.constants-V1-ndk \
    vendor.qti.hardware.data.cneaidlservice.internal.server-V1-ndk \
    vendor.qti.hardware.data.connection@1.0 \
    vendor.qti.hardware.data.connection@1.1 \
    vendor.qti.hardware.data.connectionfactory-V1-ndk \
    vendor.qti.hardware.data.dataactivity-V1-ndk \
    vendor.qti.hardware.data.dynamicdds@1.0 \
    vendor.qti.hardware.data.dynamicdds@1.1 \
    vendor.qti.hardware.data.dynamicddsaidlservice-V1-ndk \
    vendor.qti.hardware.data.flow@1.0 \
    vendor.qti.hardware.data.flow@1.1 \
    vendor.qti.hardware.data.flowaidlservice-V1-ndk \
    vendor.qti.hardware.data.iwlan@1.0 \
    vendor.qti.hardware.data.iwlan@1.1 \
    vendor.qti.hardware.data.iwlandata-V1-ndk \
    vendor.qti.hardware.data.ka-V1-ndk \
    vendor.qti.hardware.data.latency@1.0 \
    vendor.qti.hardware.data.lce@1.0 \
    vendor.qti.hardware.data.lceaidlservice-V1-ndk \
    vendor.qti.hardware.data.qmi@1.0 \
    vendor.qti.hardware.data.qmiaidlservice-V1-ndk \
    vendor.qti.hardware.dpmaidlservice-V1-ndk \
    vendor.qti.hardware.dpmservice@1.0 \
    vendor.qti.hardware.dpmservice@1.1 \
    vendor.qti.hardware.embmssl@1.0 \
    vendor.qti.hardware.embmssl@1.1 \
    vendor.qti.hardware.embmsslaidl-V2-ndk \
    vendor.qti.hardware.mwqemadapter@1.0 \
    vendor.qti.hardware.mwqemadapteraidlservice-V1-ndk \
    vendor.qti.hardware.qxr-V1-ndk \
    vendor.qti.hardware.radio.am@1.0 \
    vendor.qti.hardware.radio.lpa@1.0 \
    vendor.qti.hardware.radio.lpa@1.1 \
    vendor.qti.hardware.radio.lpa@1.2 \
    vendor.qti.hardware.radio.lpa@1.3 \
    vendor.qti.hardware.radio.qtiradio@1.0 \
    vendor.qti.hardware.radio.qtiradio@2.0 \
    vendor.qti.hardware.radio.qtiradio@2.1 \
    vendor.qti.hardware.radio.qtiradio@2.2 \
    vendor.qti.hardware.radio.qtiradio@2.3 \
    vendor.qti.hardware.radio.qtiradio@2.4 \
    vendor.qti.hardware.radio.qtiradio@2.5 \
    vendor.qti.hardware.radio.qtiradio@2.6 \
    vendor.qti.hardware.radio.qtiradio@2.7 \
    vendor.qti.hardware.radio.uim@1.0 \
    vendor.qti.hardware.radio.uim@1.1 \
    vendor.qti.hardware.radio.uim@1.2 \
    vendor.qti.hardware.radio.uim_remote_client@1.0 \
    vendor.qti.hardware.radio.uim_remote_client@1.1 \
    vendor.qti.hardware.radio.uim_remote_client@1.2 \
    vendor.qti.hardware.radio.uim_remote_server@1.0 \
    vendor.qti.hardware.slmadapter@1.0 \
    vendor.qti.imsrtpservice@3.0 \
    vendor.qti.latency@2.0 \
    vendor.qti.latency@2.1 \
    vendor.qti.latency@2.2 \
    vendor.qti.latency@2.3 \
    vendor.qti.latencyaidlservice-V1-ndk \
    CneApp \
    IWlanService \
    TimeService \
    PowerOffAlarm \
    DeviceInfo \
    DynamicDDSService \
    QtiTelephonyService \
    uceShimService \
    dpmserviceapp \
    ims \
    tcmclient \
    audiosphere \
    com.qti.dpmframework \
    com.quicinc.cne.api-V1.0-java \
    com.quicinc.cne.api-V1.1-java \
    com.quicinc.cne.constants-V1.0-java \
    com.quicinc.cne.constants-V2.0-java \
    com.quicinc.cne.constants-V2.1-java \
    dpmapi \
    qcrilhook \
    qti-telephony-common \
    vendor.qti.data.factory-V1.0-java \
    vendor.qti.data.factory-V2.0-java \
    vendor.qti.data.factory-V2.1-java \
    vendor.qti.data.factory-V2.2-java \
    vendor.qti.data.factory-V2.3-java \
    vendor.qti.data.factory-V2.4-java \
    vendor.qti.data.factory-V2.5-java \
    vendor.qti.data.factory-V2.6-java \
    vendor.qti.data.factory-V2.7-java \
    vendor.qti.data.factory-V2.8-java \
    vendor.qti.data.factoryservice-V1-java \
    vendor.qti.data.mwqem-V1.0-java \
    vendor.qti.data.mwqemaidlservice-V1-java \
    vendor.qti.data.slm-V1.0-java \
    vendor.qti.hardware.alarm-V1.0-java \
    vendor.qti.hardware.cacertaidlservice-V1-java \
    vendor.qti.hardware.capabilityconfigstore-V1.0-java \
    vendor.qti.hardware.data.cne.internal.api-V1.0-java \
    vendor.qti.hardware.data.cne.internal.constants-V1.0-java \
    vendor.qti.hardware.data.cne.internal.server-V1.0-java \
    vendor.qti.hardware.data.cne.internal.server-V1.1-java \
    vendor.qti.hardware.data.cne.internal.server-V1.2-java \
    vendor.qti.hardware.data.cne.internal.server-V1.3-java \
    vendor.qti.hardware.data.cneaidlservice.internal.api-V1-java \
    vendor.qti.hardware.data.cneaidlservice.internal.constants-V1-java \
    vendor.qti.hardware.data.cneaidlservice.internal.server-V1-java \
    vendor.qti.hardware.data.connection-V1.0-java \
    vendor.qti.hardware.data.connection-V1.1-java \
    vendor.qti.hardware.data.connectionfactory-V1-java \
    vendor.qti.hardware.data.dataactivity-V1-java \
    vendor.qti.hardware.data.dynamicdds-V1.0-java \
    vendor.qti.hardware.data.dynamicdds-V1.1-java \
    vendor.qti.hardware.data.dynamicddsaidlservice-V1-java \
    vendor.qti.hardware.data.flow-V1.0-java \
    vendor.qti.hardware.data.flow-V1.1-java \
    vendor.qti.hardware.data.flowaidlservice-V1-java \
    vendor.qti.hardware.data.iwlan-V1.0-java \
    vendor.qti.hardware.data.iwlan-V1.1-java \
    vendor.qti.hardware.data.iwlandata-V1-java \
    vendor.qti.hardware.data.ka-V1-java \
    vendor.qti.hardware.data.latency-V1.0-java \
    vendor.qti.hardware.data.lce-V1.0-java \
    vendor.qti.hardware.data.lceaidlservice-V1-java \
    vendor.qti.hardware.data.qmi-V1.0-java \
    vendor.qti.hardware.data.qmiaidlservice-V1-java \
    vendor.qti.hardware.dpmaidlservice-V1-java \
    vendor.qti.hardware.dpmservice-V1.0-java \
    vendor.qti.hardware.dpmservice-V1.1-java \
    vendor.qti.hardware.mwqemadapter-V1.0-java \
    vendor.qti.hardware.mwqemadapteraidlservice-V1-java \
    vendor.qti.hardware.sensorscalibrate-V1.0-java \
    vendor.qti.hardware.slmadapter-V1.0-java \
    vendor.qti.latency-V2.0-java \
    vendor.qti.latency-V2.1-java \
    vendor.qti.latency-V2.2-java \
    vendor.qti.latencyaidlservice-V1-java \
    manifest_android.hardware.drm@1.4-service.widevine.xml \
    vendor.qti.gnss@4.3-service.xml \
    adpl \
    adsprpcd \
    audioflacapp \
    cdsprpcd \
    cnd \
    cnss-daemon \
    dpmQmiMgr \
    dspservice \
    garden_app \
    hvdcp_opti \
    android.hardware.bluetooth@1.0-service-qti \
    android.hardware.drm@1.4-service.widevine \
    android.hardware.gatekeeper@1.0-service-qti \
    android.hardware.keymaster@3.0-service-qti \
    android.hardware.keymaster@4.0-service-qti \
    qcrild \
    vendor.display.color@1.0-service \
    vendor.qti.esepowermanager@1.1-service \
    vendor.qti.hardware.alarm@1.0-service \
    vendor.qti.hardware.capabilityconfigstore@1.0-service \
    vendor.qti.hardware.qseecom@1.0-service \
    vendor.qti.hardware.qteeconnector@1.0-service \
    vendor.qti.hardware.soter@1.0-service \
    vendor.qti.hardware.tui_comm@1.0-service-qti \
    ims_rtp_daemon \
    imsdatadaemon \
    imsqmidaemon \
    imsrcsd \
    irsc_util \
    loadalgo \
    loc_launcher \
    lowi-server \
    mlipayd@1.1 \
    mm-pp-dpps \
    msm_irqbalance \
    netmgrd \
    pd-mapper \
    pm-proxy \
    pm-service \
    port-bridge \
    power_off_alarm \
    qrtr-cfg \
    qrtr-lookup \
    qrtr-ns \
    qseecomd \
    qti \
    rmt_storage \
    sensors.qti \
    slim_daemon \
    tftp_server \
    thermal-engine \
    time_daemon \
    xtra-daemon \
    dpmd \
    qxrsplitauxservice

PRODUCT_PACKAGES += \
    system_ext_priv-app_ims_lib_arm64_libimscamera_jni_so \
    system_ext_priv-app_ims_lib_arm64_libimsmedia_jni_so \
    vendor_lib_libEGL_adreno_so \
    vendor_lib_libGLESv2_adreno_so \
    vendor_lib_libq3dtools_adreno_so \
    vendor_lib64_libEGL_adreno_so \
    vendor_lib64_libGLESv2_adreno_so \
    vendor_lib64_libq3dtools_adreno_so
